- cxx-qt-gen/src/extract.rs
- cxx-qt-gen/src/gen_rs.rs
Change-Id: I8b0bde82ea5cf88fe640e8c279d39f7de03364b0
> extract: fix clippy warnings and remove dead code

- cxx-qt-gen/src/cxx_qt.cpp
- cxx-qt-lib/src/qvariant.rs
- examples/basic_cxx_qt_qml/src/mock_qt_types.rs
- examples/basic_cxx_qt_qml_plugin/src/mock_qt_types.rs
- examples/qt_types_standalone/src/lib.rs
- examples/qt_types_standalone/src/main.cpp
> QVariant add primitives support

- .github/workflows/github-cxx-qt-tests.yml
- CMakeLists.txt
- examples/basic_cxx_qt_qml_plugin/CMakeLists.txt
- valgrind_suppressions.txt
Change-Id: I688fadf16830b9bdeef6100b5d578ccdf9941023
> ci: add github actions CI for ctest

- .github/workflows/book.yml
- .github/workflows/manual-book.yml
Change-Id: Id72dcb526664e745e36b3e059898a3833b24e73b
> github: add mdbook-linkcheck to CI for books

- .github/workflows/book.yml
- .github/workflows/manual-book.yml
- cxx-qt-gen/src/extract.rs
- cxx-qt-gen/src/gen_rs.rs
- cxx-qt/src/lib.rs
Change-Id: I01beceb87f0685b4f88a4c00b33fd0295388a356
> github: use the html subdir from the book as the root folder for pages

- book/src/SUMMARY.md
- book/src/concepts/index.md
- book/src/concepts/qqmlextensionplugin.md
Change-Id: I22e81a80d72335786ab4a8c7dd9cb3de4d85750e
> book: add qqmlextensionplugin concept

- book/src/images/threading_abstract.svg
Change-Id: I41d72b7c78f6627930d09aba98fdea37de806249
> book: refresh threading_abstract image so it include white line

- README.md
- cxx-qt-gen/src/cxx_qt.cpp
Change-Id: I928f4615a20876f947bd3210433bc10719b2b299
> cxx-qt: support Qt 6 in our Qt code

- README.md
Change-Id: I014e725f9795d0afb25974382c2055a1e998a135
> README: include getting started example

- README.md
- book/src/getting-started/index.md
- book/src/index.md
Change-Id: Id2219f16bcc0ff47eaf5cb6d11f2206caa6b5f25
> README: note Linux only support for now

- cxx-qt-build/src/lib.rs
CMake's `file(STRINGS)` command fails if \ and / path separators
are mixed, or if all \ separators are used.
> cxx-qt-build: use / path separators on Windows for generated files

- CMakeLists.txt
- cmake/CxxQt.cmake
> build in debug mode by default

- examples/qml_features/src/main.qml
Change-Id: I85e8768742b11f19d2052bda31de1fe91f7f9bff
> qml_features: update QML to use new naming

- cxx-qt-gen/src/gen_rs.rs
- cxx-qt-gen/test_outputs/basic_mod_attrs_vis.rs
- cxx-qt-gen/test_outputs/basic_only_invokable.rs
- cxx-qt-gen/test_outputs/basic_only_invokable_return.rs
- cxx-qt-gen/test_outputs/basic_pin_invokable.rs
- cxx-qt-gen/test_outputs/basic_unknown_rust_obj_type.rs
- cxx-qt-gen/test_outputs/basic_update_requester.rs
- cxx-qt-gen/test_outputs/subobject_pin_invokable.rs
- cxx-qt-gen/test_outputs/types_qt_invokable.rs
- examples/qml_features/build.rs
- examples/qml_features/src/empty.rs
- examples/qml_features/src/lib.rs
Closes #96
Change-Id: I30e46ed2b4fb4cefe30f733e78ca0c3bf2c07be4
> cxx-qt-gen: only generate Property enum when there are properties

- valgrind_suppressions.txt
Change-Id: I0793561b1579f2be6667bf16273cbc7f14a514ab
> valgrind: add suppressions to handle leaks from Nvidia 470 driver

- README.md
- cxx-qt-gen/src/extract.rs
- cxx-qt-gen/test_inputs/passthrough.rs
- cxx-qt-gen/test_outputs/passthrough.rs
- examples/qml_extension_plugin/core/src/lib.rs
> extract: passthrough all unknown types

- README.md
- book/src/concepts/cmake.md
- cxx-qt/README.md
Change-Id: I996db30cbb1eee9ee8b3239d5799fdc10a3d0e92
> metadata: use CXX-Qt instead of cxx-qt in text

- .github/workflows/github-cxx-qt-tests.yml
which was released a few weeks ago 04-05-2022
> GH Actions: update sccache to 0.3.0

- book/src/concepts/qt.md
- book/src/qobject/cpp_object.md
- book/src/qobject/signals_enum.md
- cxx-qt-gen/src/extract.rs
- cxx-qt-gen/src/gen_cpp.rs
- cxx-qt-gen/src/gen_rs.rs
- cxx-qt-gen/test_inputs/signals.rs
- cxx-qt-gen/test_inputs/signals.rs.license
- cxx-qt-gen/test_outputs/signals.cpp
- cxx-qt-gen/test_outputs/signals.cpp.license
- cxx-qt-gen/test_outputs/signals.h
- cxx-qt-gen/test_outputs/signals.h.license
- cxx-qt-gen/test_outputs/signals.rs
- cxx-qt-gen/test_outputs/signals.rs.license
- examples/qml_features/build.rs
- examples/qml_features/src/lib.rs
- examples/qml_features/src/mock_qt_types.rs
- examples/qml_features/src/signals.rs
- examples/qml_features/src/tests/qttypes/tst_qttypes.qml
Closes #31
Change-Id: Id3781124f0090c0f69517d346ccefb33b6df000d
> cxx-qt-gen: add support for declaring and emitting signals 

- book/src/concepts/build_rs_and_cargo.md
- cxx-qt-build/Cargo.toml
- cxx-qt-gen/Cargo.toml
- cxx-qt-lib/Cargo.toml
- cxx-qt/Cargo.toml
- examples/demo_threading/Cargo.toml
- examples/qml_extension_plugin/core/Cargo.toml
- examples/qml_features/Cargo.toml
- examples/qml_minimal/Cargo.toml
- examples/qml_with_threaded_logic/Cargo.toml
- tests/basic_cxx_only/Cargo.toml
- tests/basic_cxx_qt/Cargo.toml
- tests/qt_types_standalone/Cargo.toml
- vcpkg.json
Change-Id: I1370a42eef1e665fa36f70626aecd86af507bedd
> release: bump to 0.3.0 release

- README.md
- book/src/getting-started/2-our-first-cxx-qt-module.md
- book/src/getting-started/5-cmake-integration.md
- book/src/qobject/macro.md
- cxx-qt-build/src/lib.rs
- cxx-qt-gen/src/gen_rs.rs
- cxx-qt-gen/test_inputs/passthrough.rs
- cxx-qt/src/lib.rs
- examples/demo_threading/src/lib.rs
- examples/qml_extension_plugin/core/src/lib.rs
- examples/qml_features/src/data_struct_properties.rs
- examples/qml_features/src/empty.rs
- examples/qml_features/src/handler_property_change.rs
- examples/qml_features/src/lib.rs
- examples/qml_features/src/mock_qt_types.rs
- examples/qml_features/src/nested.rs
- examples/qml_features/src/rust_obj_invokables.rs
- examples/qml_features/src/serialisation.rs
- examples/qml_features/src/signals.rs
- examples/qml_features/src/sub.rs
- examples/qml_features/src/types.rs
- examples/qml_minimal/src/lib.rs
- examples/qml_with_threaded_logic/src/lib.rs
- tests/basic_cxx_qt/src/data.rs
- tests/basic_cxx_qt/src/lib.rs
- tests/basic_cxx_qt/src/sub.rs
- tests/basic_cxx_qt/src/types.rs
Change-Id: Icdd8537ee00b9772aaf68dc0b4c6fb38f8704000
> macro: rename make_qobject to cxx_qt::bridge

- cxx-qt-lib/build.rs
These C++ files won't build yet because the #include paths need to
be adjusted.
> cxx-qt-lib: add option to output C++ to CXX_QT_LIB_OUT_DIR env var

- book/src/SUMMARY.md
- book/src/concepts/type-conversions.md
- cxx-qt-lib/include/qt_types.h
- Fix return-by-reference conversions.
- Better error messages.
- Explanation in the book.
> Improve type conversions

- .github/workflows/github-cxx-qt-tests.yml
- cxx-qt-lib/src/qt_types.cpp
- valgrind_suppressions.txt
fixes https://github.com/KDAB/cxx-qt/issues/121
> GH Actions: switch to Ubuntu 22.04, stop using PPAs

- .github/workflows/github-cxx-qt-tests.yml
Hopefully this results in less cache misses.
> GH Actions: set limit on sccache cache size

- cxx-qt-gen/src/extract.rs
- cxx-qt-gen/src/gen_rs.rs
- cxx-qt-gen/src/parser/mod.rs
- cxx-qt-gen/src/parser/parameter.rs
- cxx-qt-gen/src/parser/qobject.rs
- cxx-qt-gen/src/parser/signals.rs
- cxx-qt-gen/src/syntax/fields.rs
- cxx-qt-gen/src/syntax/mod.rs
- cxx-qt-gen/src/syntax/path.rs
For now the extract phase still needs to convert this into it's own Signal. But later this will happen in the generate phase.
Requires #187
> cxx-qt-gen: add ParsedSignal to parser

- cxx-qt-gen/src/gen_rs.rs
- cxx-qt-gen/src/generator/mod.rs
- cxx-qt-gen/src/generator/rust/mod.rs
- cxx-qt-gen/src/writer/mod.rs
- cxx-qt-gen/src/writer/rust/mod.rs
- cxx-qt-gen/test_outputs/handlers.rs
> cxx-qt-gen: add a writer phase for the Rust side

- cxx-qt-gen/src/gen_rs.rs
- cxx-qt-gen/src/generator/rust/mod.rs
- cxx-qt-gen/src/writer/rust/mod.rs
- cxx-qt-gen/test_outputs/custom_default.rs
- cxx-qt-gen/test_outputs/handlers.rs
- cxx-qt-gen/test_outputs/invokables.rs
- cxx-qt-gen/test_outputs/naming.rs
- cxx-qt-gen/test_outputs/passthrough.rs
- cxx-qt-gen/test_outputs/properties.rs
- cxx-qt-gen/test_outputs/signals.rs
- cxx-qt-gen/test_outputs/types_primitive_property.rs
- cxx-qt-gen/test_outputs/types_qt_invokable.rs
- cxx-qt-gen/test_outputs/types_qt_property.rs
> cxx-qt-gen: inject the CXX definition for common methods in writer

- cxx-qt-lib/Cargo.toml
- examples/cargo_without_cmake/Cargo.toml
- examples/demo_threading/Cargo.toml
- examples/qml_extension_plugin/core/Cargo.toml
- examples/qml_features/Cargo.toml
- examples/qml_minimal/Cargo.toml
- examples/qml_with_threaded_logic/Cargo.toml
- tests/basic_cxx_only/Cargo.toml
- tests/basic_cxx_qt/Cargo.toml
- tests/qt_types_standalone/Cargo.toml
This includes the fix to allow for Unpin impl on UniquePtr
> cargo: use cxx version 1.0.75 or greater

- README.md
We do not have the code in this example built and tested, so it is cumbersome to keep up-to-date. It also makes the README rather crowded. Instead, refer readers to the book and examples.
> README: remove inline example

- examples/qml_features/CMakeLists.txt
- examples/qml_features/cpp/qabstractlistmodelcxx.h
- examples/qml_features/qml/main.qml
- examples/qml_features/rust/build.rs
- examples/qml_features/rust/src/custom_base.rs
> examples: manually implement a listmodel

- CHANGELOG.md
- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
- crates/cxx-qt-gen/test_inputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.cpp
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.h
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- examples/README.md
- examples/qml_features/CMakeLists.txt
- examples/qml_features/cpp/main.cpp
- examples/qml_features/qml/main.qml
- examples/qml_features/qml/pages/MultipleQObjectsPage.qml
- examples/qml_features/qml/qml.qrc
- examples/qml_features/rust/build.rs
- examples/qml_features/rust/src/lib.rs
- examples/qml_features/rust/src/multiple_qobjects.rs
- examples/qml_features/tests/main.cpp
- examples/qml_features/tests/tst_multiple_qobjects.qml
> parser: allow multiple QObjects in a single block and add tests

- examples/cargo_without_cmake/CMakeLists.txt
- examples/demo_threading/CMakeLists.txt
- examples/qml_extension_plugin/plugin/CMakeLists.txt
- examples/qml_features/CMakeLists.txt
- examples/qml_minimal/CMakeLists.txt
> corrosion: bump to v0.3.0 for our examples 

- crates/cxx-qt-gen/src/parser/invokable.rs
- crates/cxx-qt-gen/src/parser/parameter.rs
- crates/cxx-qt-gen/src/parser/qobject.rs
- crates/cxx-qt-gen/src/syntax/implitemmethod.rs
Extract their parsing into their own `parse` methods.
> ParsedQInvokable, ParsedFunctionParameter Refactor

- crates/cxx-qt-lib/src/types/qlist/mod.rs
> fix copypasta typos in QList documentation

- README.md
Should make our repository a bit more colorful and engaging.
> Add shields to the README

- CHANGELOG.md
Follow up to https://github.com/KDAB/cxx-qt/pull/428
> add QML and QRC registration to CHANGELOG

- crates/cxx-qt-gen/src/generator/cpp/qobject.rs
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
- crates/cxx-qt-gen/src/parser/qobject.rs
- examples/qml_features/CMakeLists.txt
- examples/qml_features/qml/main.qml
- examples/qml_features/qml/pages/SingletonPage.qml
- examples/qml_features/qml/qml.qrc
- examples/qml_features/rust/build.rs
- examples/qml_features/rust/src/lib.rs
- examples/qml_features/rust/src/singleton.rs
- examples/qml_features/rust/src/uncreatable.rs
- examples/qml_features/tests/tst_singleton.qml
- examples/qml_features/tests/tst_uncreatable.qml
> cxx-qt-gen: qml_singleton support

- CMakeLists.txt
Variable was set to an update string, this shouldn't affect anything in the project.
fix #467
> fix `COMMAND_PREIFX` -> `COMMAND_PREFIX`

- CHANGELOG.md
- crates/qt-build-utils/src/lib.rs
> cxx-qt-build: if files in the qrc file change rerun cargo

- CHANGELOG.md
- crates/cxx-qt-lib/src/core/qvariant/mod.rs
> Implement PartialEq for QVariant

- crates/cxx-qt-gen/Cargo.toml
- examples/cargo_without_cmake/CMakeLists.txt
- examples/demo_threading/CMakeLists.txt
- examples/qml_extension_plugin/plugin/CMakeLists.txt
- examples/qml_features/CMakeLists.txt
- examples/qml_minimal/CMakeLists.txt
Other outdated libraries found while bumping syn.
> Bump ctor and corrosion

- book/src/getting-started/4-cmake-integration.md
- book/src/getting-started/5-cargo-executable.md
> cxx-qt-build: Add more information about qmake, how it is used and why

- CHANGELOG.md
- Cargo.toml
- crates/cxx-qt-build/src/lib.rs
Cherry pick https://github.com/KDAB/cxx-qt/commit/8e6522bb258d61403fe14b315341ddbed5dbb1d7
> 0.5.2 release

- CHANGELOG.md
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
- crates/cxx-qt-gen/src/parser/qobject.rs
- crates/cxx-qt-gen/test_inputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- examples/qml_features/rust/src/custom_base_class.rs
> Allow associated constants in `impl qobject::T`

- crates/cxx-qt-gen/src/generator/rust/field.rs
- crates/cxx-qt-gen/src/generator/rust/property/getter.rs
- crates/cxx-qt-gen/src/generator/rust/property/mod.rs
- crates/cxx-qt-gen/test_outputs/inheritance.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.rs
> Stop generating `mut` on self pins unnecessarily

- CHANGELOG.md
- book/src/concepts/threading.md
- book/src/qobject/cxxqtthread.md
- crates/cxx-qt-gen/src/generator/cpp/invokable.rs
- crates/cxx-qt-gen/src/generator/cpp/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/property/getter.rs
- crates/cxx-qt-gen/src/generator/cpp/property/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/property/setter.rs
- crates/cxx-qt-gen/src/generator/cpp/qobject.rs
- crates/cxx-qt-gen/src/generator/cpp/signal.rs
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/src/parser/qobject.rs
- crates/cxx-qt-gen/src/writer/cpp/header.rs
- crates/cxx-qt-gen/src/writer/cpp/mod.rs
- crates/cxx-qt-gen/src/writer/cpp/source.rs
- crates/cxx-qt-gen/test_inputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/inheritance.rs
- crates/cxx-qt-gen/test_outputs/invokables.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.cpp
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.h
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-gen/test_outputs/signals.rs
- crates/cxx-qt/src/lib.rs
- tests/basic_cxx_qt/cpp/main.cpp
- tests/basic_cxx_qt/rust/build.rs
- tests/basic_cxx_qt/rust/src/lib.rs
- tests/basic_cxx_qt/rust/src/locking.rs
> cxx-qt-gen: add cxx_qt::Locking as a trait which can be negated

- CHANGELOG.md
- crates/cxx-qt-gen/src/generator/rust/property/getter.rs
- crates/cxx-qt-gen/src/generator/rust/property/mod.rs
- crates/cxx-qt-gen/src/generator/rust/property/setter.rs
- crates/cxx-qt-gen/src/writer/rust/mod.rs
- crates/cxx-qt-gen/test_outputs/inheritance.rs
- crates/cxx-qt-gen/test_outputs/invokables.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-gen/test_outputs/signals.rs
- examples/demo_threading/rust/src/lib.rs
- examples/qml_features/rust/src/custom_base_class.rs
- examples/qml_features/rust/src/invokables.rs
- examples/qml_features/rust/src/signals.rs
- tests/basic_cxx_qt/rust/src/lib.rs
- tests/basic_cxx_qt/rust/src/locking.rs
> cxx-qt-gen: impl Deref for qobject::T to reach T easily

- crates/cxx-qt-gen/src/generator/rust/property/getter.rs
- crates/cxx-qt-gen/src/generator/rust/property/mod.rs
- crates/cxx-qt-gen/src/generator/rust/property/setter.rs
- crates/cxx-qt-gen/src/generator/rust/signals.rs
- crates/cxx-qt-gen/src/generator/utils/rust.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-gen/test_outputs/signals.rs
> cxx-qt-gen: fully qualify bridge parameters in implementations

- .github/workflows/github-cxx-qt-tests.yml
- CMakeLists.txt
- check_cargo_build_rerun.sh
- crates/cxx-qt-build/src/lib.rs
- crates/qt-build-utils/src/lib.rs
> qt-build-utils: do not rerun when generated QML module files change

- book/src/bridge/extern_rustqt.md
- book/src/concepts/build_systems.md
- book/src/concepts/inheritance.md
> book: reduce extern RustQt TODOs

- README.md
(We need to open it in browser at specific url)
> Add info about how ready last documentation.

- CMakeLists.txt
- tests/CMakeLists.txt
Valgrind can't be use on windows.
> Remove valgrind warning on windows

- crates/cxx-qt-lib/Cargo.toml
from_naive_utc_and_offset was missing
> Fix minimum supported chrono version

- crates/cxx-qt-gen/src/generator/rust/constructor.rs
- crates/cxx-qt-gen/src/generator/rust/inherit.rs
- crates/cxx-qt-gen/src/generator/rust/method.rs
- crates/cxx-qt-gen/src/generator/rust/qenum.rs
- crates/cxx-qt-gen/test_outputs/invokables.rs
unsure if everything is covered
https://github.com/KDAB/cxx-qt/issues/637
> generator: use quote_spanned! where possible

- crates/cxx-qt-build/src/lib.rs
Fixes https://github.com/KDAB/cxx-qt/issues/826
> cxx-qt-build: update documentation for `qrc` method

- crates/cxx-qt-lib-headers/include/core/qdatetime.h
- crates/cxx-qt-lib/src/core/qdatetime.cpp
- crates/cxx-qt-lib/src/core/qdatetime.rs
> In qt6.7: QDateTime::setTimezone overload breaks compilation

- .github/workflows/github-cxx-qt-tests.yml
The `&&` has to be *within* the curly braces
> Fix CI conditional cache deletion.

- crates/cxx-qt-lib/src/gui/qfont.rs
- crates/cxx-qt-lib/src/gui/qimage.rs
- crates/cxx-qt-lib/src/gui/qpainterpath.rs
- crates/cxx-qt-lib/src/gui/qpen.rs
- crates/cxx-qt-lib/src/gui/qpolygon.rs
- crates/cxx-qt-lib/src/gui/qpolygonf.rs
> Implement PartialEq

- crates/cxx-qt-gen/src/generator/cpp/fragment.rs
- crates/cxx-qt-gen/src/generator/cpp/mod.rs
- crates/cxx-qt-gen/src/generator/rust/mod.rs
- crates/cxx-qt-gen/src/lib.rs
- crates/cxx-qt-gen/src/parser/mod.rs
- crates/cxx-qt-gen/src/syntax/mod.rs
- crates/cxx-qt-gen/src/syntax/qtfile.rs
- crates/cxx-qt-gen/src/syntax/qtitem.rs
- crates/qt-build-utils/src/lib.rs
> crates: deny missing docs for more crates

- crates/cxx-qt-build/src/lib.rs
- crates/cxx-qt-lib/build.rs
- crates/cxx-qt-lib/src/core/qbytearray.rs
- crates/cxx-qt-lib/src/core/qlist/mod.rs
- crates/cxx-qt-lib/src/core/qstring.rs
- crates/cxx-qt-lib/src/core/qstringlist.rs
- crates/cxx-qt-lib/src/core/qvariant/mod.rs
- crates/cxx-qt-lib/src/core/qvector/mod.rs
- crates/cxx-qt-lib/src/gui/qimage.rs
- crates/cxx-qt-lib/src/gui/qpen.rs
- crates/cxx-qt-lib/src/gui/qpolygon.rs
- crates/cxx-qt-lib/src/gui/qpolygonf.rs
- crates/cxx-qt-lib/src/lib.rs
This is generally useful everywhere so lets set it.
> cxx-qt-build: always set cxxqt_qt_major_version

- CMakeLists.txt
- tests/CMakeLists.txt
> Add info when we found Valgrind + don't failed when we don't find

- Cargo.toml
- crates/cxx-qt-build/src/cfg_evaluator.rs
- crates/cxx-qt-build/src/lib.rs
- crates/cxx-qt-lib/src/gui/qimage.rs
> cxx-qt-build: set a cfg_evaluator so that we can use cfg attributes

- CHANGELOG.md
- crates/cxx-qt-lib/Cargo.toml
- crates/cxx-qt-lib/src/core/qstring.rs
- examples/qml_features/rust/Cargo.toml
- examples/qml_features/rust/src/serialisation.rs
> feat: lib: Serde support for QString

- crates/cxx-qt-build/src/lib.rs
Otherwise you get build warnings when using rustc-cfg attributes.
https://blog.rust-lang.org/2024/05/06/check-cfg.html
> build: for Rust 1.80 we need to specify rustc-check-cfg

- crates/qt-build-utils/Cargo.toml
- crates/qt-build-utils/src/lib.rs
Otherwise we get a clippy error in CI
> chore: Bump version of versions crate

- CHANGELOG.md
- book/src/bridge/extern_rustqt.md
- book/src/getting-started/2-our-first-cxx-qt-module.md
- crates/cxx-qt-gen/src/generator/cpp/property/meta.rs
- crates/cxx-qt-gen/src/generator/cpp/property/mod.rs
- crates/cxx-qt-gen/src/generator/naming/property.rs
- crates/cxx-qt-gen/src/naming/type_names.rs
- crates/cxx-qt-gen/src/parser/property.rs
- crates/cxx-qt-gen/test_inputs/properties.rs
- crates/cxx-qt-gen/test_outputs/properties.cpp
- crates/cxx-qt-gen/test_outputs/properties.h
- crates/cxx-qt-gen/test_outputs/properties.rs
Constant, Reset and Required are now supported, with final as a WIP (see [issue #1002](https://github.com/KDAB/cxx-qt/issues/1002))
> Add support for new QProperty flags (Reset, Constant, Required, Final)

- crates/cxx-qt-gen/src/generator/cpp/method.rs
- crates/cxx-qt-gen/src/generator/mod.rs
- crates/cxx-qt-gen/src/generator/rust/method.rs
- crates/cxx-qt-gen/src/generator/rust/signals.rs
- crates/cxx-qt-gen/src/parser/method.rs
- crates/cxx-qt-gen/src/parser/signals.rs
Created some helper functions for ParsedMethod and ParsedSignal to improve readability of tests and generator code, some of which were quite long and verbose
> Clean up some long functions and tests

- crates/cxx-qt-gen/src/parser/constructor.rs
- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
- crates/cxx-qt-gen/src/parser/externcxxqt.rs
- crates/cxx-qt-gen/src/parser/parameter.rs
- crates/cxx-qt-gen/src/parser/property.rs
- crates/cxx-qt-gen/src/parser/qobject.rs
- crates/cxx-qt-gen/src/parser/signals.rs
Improve the code coverage for the parser directory in cxx-qt-gen
> Improve code coverage in parser

- crates/cxx-qt-gen/src/generator/cpp/property/getter.rs
- crates/cxx-qt-gen/src/generator/cpp/property/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/property/setter.rs
- crates/cxx-qt-gen/src/generator/cpp/property/signal.rs
- crates/cxx-qt-gen/src/generator/rust/constructor.rs
- crates/cxx-qt-gen/src/generator/rust/cxxqttype.rs
- crates/cxx-qt-gen/src/generator/rust/externcxxqt.rs
- crates/cxx-qt-gen/src/generator/rust/inherit.rs
- crates/cxx-qt-gen/src/generator/rust/method.rs
- crates/cxx-qt-gen/src/generator/rust/mod.rs
- crates/cxx-qt-gen/src/generator/rust/property/getter.rs
- crates/cxx-qt-gen/src/generator/rust/property/mod.rs
- crates/cxx-qt-gen/src/generator/rust/property/setter.rs
- crates/cxx-qt-gen/src/generator/rust/property/signal.rs
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/src/generator/rust/signals.rs
- crates/cxx-qt-gen/src/generator/rust/threading.rs
- crates/cxx-qt-gen/src/naming/name.rs
- crates/cxx-qt-gen/src/parser/qobject.rs
Update and rename some aspects surrounding name usage, and fix a bug with qml_element generation
> Refactor fix name usage

- CHANGELOG.md
- crates/cxx-qt-lib/Cargo.toml
- examples/cargo_without_cmake/Cargo.toml
- examples/demo_threading/rust/Cargo.toml
- examples/qml_features/rust/Cargo.toml
- examples/qml_minimal/rust/Cargo.toml
- tests/basic_cxx_qt/rust/Cargo.toml
- tests/qt_types_standalone/rust/Cargo.toml
Add support to solve this issue: #1011
> Make features Opt in

- .github/workflows/github-cxx-qt-tests.yml
- book/src/getting-started/6-wasm-builds.md
Closes #414 (note #947 for further wasm code)
> Add CI runner for WASM build

- crates/cxx-qt-gen/src/generator/rust/threading.rs
- crates/cxx-qt-gen/test_outputs/invokables.rs
> cxx-qt-gen: ensure that threading struct is in right namespace

- book/src/SUMMARY.md
- book/src/internals/crate-organization.md
We've discussed this many times. Let's finally put it in writing.
> Book: Add internal section for crate-organization

- CHANGELOG.md
- Cargo.toml
- examples/qml_basics/Cargo.toml
- examples/qml_basics/build.rs
- examples/qml_basics/qml/main.qml
- examples/qml_basics/src/main.rs
This is the code developed during the second tutorial video:
https://www.youtube.com/watch?v=fdikaBcTgSM
It goes slightly beyond the minimal example, so add it as it's own
project.
It should also serve as a reference for backwards-compatibility.
> Add "Basics" tutorial

- .github/workflows/github-cxx-qt-tests.yml
> ci: bump sccache to 0.9.1

- Cargo.lock
- Cargo.toml
Bump CXX version to include @ahayzen-kdab fix.
> Update CXX version

- crates/cxx-qt-gen/src/parser/externcxxqt.rs
> Add check for inherit attr in C++Qt blocks

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- book/src/getting-started/5-cmake-integration.md
- **Add changelog for 0.7.2**
- **Bump version to 0.7.2**
> Sync 0.7.2 changes back to main

- book/src/getting-started/2-our-first-cxx-qt-module.md
I hope my understanding is correct
> book: CXX instead of CXX-Qt for the piece that translate types to cpp

- .github/workflows/github-cxx-qt-tests.yml
This should enable us to enable the Merge queue.
> Add merge_group hook to CI workflows

- crates/cxx-qt-lib/src/core/qlist/mod.rs
- crates/cxx-qt-lib/src/core/qset/mod.rs
- crates/cxx-qt-lib/src/core/qvector/mod.rs
- crates/cxx-qt-lib/src/serde_impl.rs
Also implements Extend, which is used for the implementations of FromIterator.
> Implement FromIterator for QList, QSet, and QVector

- crates/cxx-qt-build/src/diagnostics.rs
- crates/cxx-qt-build/src/lib.rs
- crates/cxx-qt-gen/src/generator/cfg.rs
- crates/cxx-qt-gen/src/generator/cpp/method.rs
- crates/cxx-qt-gen/src/generator/rust/constructor.rs
- crates/cxx-qt-gen/src/generator/rust/cxxqttype.rs
- crates/cxx-qt-gen/src/generator/rust/signals.rs
- crates/cxx-qt-gen/src/generator/rust/threading.rs
- crates/cxx-qt-gen/src/lib.rs
- crates/cxx-qt-gen/src/syntax/qtitem.rs
- crates/cxx-qt-gen/src/writer/cpp/header.rs
- crates/cxx-qt-lib/src/gui/qcolor.rs
- crates/qt-build-utils/src/installation/qmake.rs
- crates/qt-build-utils/src/lib.rs
Somehow a few lint warnings got through.
> Run cargo clippy --fix
