- examples/basic_cxx_qt_qml/src/mock_qt_types.rs
- examples/basic_cxx_qt_qml/src/tests/qttypes/tst_qttypes.qml
- examples/basic_cxx_qt_qml_plugin/src/mock_qt_types.rs
- examples/basic_cxx_qt_qml_plugin/src/tests/tst_qttypes.qml
Change-Id: Ie3d7048f35807ca790dfb6567e7d3e9d77910156
> examples: fix qpointf test to ensure it uses y property

- cxx-qt-gen/src/gen_cpp.rs
Change-Id: I17db117ad7a3344fa11d303011bde09cbdfd404d
> gen_cpp: fix new clippy 1.58 warnings

- .github/workflows/github-cxx-qt-tests.yml
- .gitmodules
- CMakeLists.txt
- LICENSES/BSD-3-Clause.txt
- README.md
- clang_format_check.sh
- cmake/CompilerCaching.cmake
- cmake/CxxQt.cmake
- cmake/InitializeVcpkg.cmake
- examples/qml_extension_plugin/CMakeLists.txt
- examples/qml_extension_plugin/core/CMakeLists.txt
- examples/qml_features/CMakeLists.txt
- examples/qml_minimal/CMakeLists.txt
- examples/qml_with_threaded_logic/CMakeLists.txt
- tests/basic_cxx_only/CMakeLists.txt
- tests/basic_cxx_qt/CMakeLists.txt
- tests/qt_types_standalone/CMakeLists.txt
- tests/update_requester_standalone/CMakeLists.txt
- vcpkg.json
- vcpkg.json.license
This builds Qt with vcpkg and caches the C++ dependencies on GitHub Packages. The builds work on Linux, Windows, and macOS for both Qt5 and Qt6, however the tests only pass on Linux. It uses sccache for both C++ and Rust to speed up the builds.
Currently it is using GitHub Packages under my GitHub user because that is what I have write access to. GITHUB_TOKEN can only have write access to the KDAB organization's GitHub Packages for a pull request from a branch on the upstream repository; it only has read access for pull requests from forked repositories. When this is merged, `Be-ing` should be replaced with `KDAB` in the `Authenticate to GitHub Packages` step of the GitHub Actions workflow and a GitHub Personal Access Token with read-only permission to packages generated for anonymous …
> use vcpkg for Windows & macOS builds; add Qt6 builds; use sccache

- examples/qml_features/src/tests/qttypes/tst_qttypes.qml
Tests would fail when running in different timezones due to
QDate being converted to and from QDateTime.
Change-Id: I214c4d21125d33ae0a106447dc4c7d41ce5b6142
> qdate: fix tests failing in different timezones

- cxx-qt-gen/src/extract.rs
- cxx-qt-gen/src/gen_rs.rs
- cxx-qt-gen/test_inputs/basic_only_invokable.rs
- cxx-qt-gen/test_inputs/basic_pin_invokable.rs
- cxx-qt-gen/test_outputs/basic_only_invokable.cpp
- cxx-qt-gen/test_outputs/basic_only_invokable.h
- cxx-qt-gen/test_outputs/basic_only_invokable.rs
- cxx-qt-gen/test_outputs/basic_pin_invokable.rs
- examples/qml_features/src/rust_obj_invokables.rs
This allows for invokables to mutate the RustObj
This came from #41, I thought i'd split it out so it can land earlier as it's useful.
> invokable: support &mut self and self for invokables

- book/src/getting-started/2-our-first-cxx-qt-module.md
- book/src/getting-started/3-exposing-to-qml.md
- book/src/getting-started/5-cmake-integration.md
- examples/qml_minimal/CMakeLists.txt
- examples/qml_minimal/Cargo.toml
- examples/qml_minimal/src/qml.qrc
As we specify PRIVATE in CxxQt.cmake further uses on the target
need to use PRIVATE or PUBLIC.
Closes #129
Change-Id: I0af585264a5859d77dd4a56b7178dfaf93852da5
> book: specify PRIVATE when using target_link_libaries

- cxx-qt-gen/src/gen_cpp.rs
- cxx-qt-gen/test_outputs/handlers.cpp
- cxx-qt-gen/test_outputs/naming.cpp
- cxx-qt-gen/test_outputs/properties.cpp
- cxx-qt-gen/test_outputs/types_primitive_property.cpp
- cxx-qt-gen/test_outputs/types_qt_property.cpp
In release mode signals and handlers were missed due to Q_ASSERT
being optimised out.
Change-Id: I3db834ee3851d4f9266115eeef06ed8534804c21
> gen_cpp: ensure that Q_ASSERT in release mode won't break invokeMethods

- .github/workflows/github-cxx-qt-tests.yml
This ensures that we pick up any failures from code being
optimised out inside Q_ASSERT etc.
Change-Id: Ie83484c98790c8db944b692650cdb9c6fb2d1d26
> ci: use release builds for tests

- book/src/concepts/build_rs_and_cargo.md
- cxx-qt-build/src/lib.rs
- cxx-qt/src/lib.rs
- examples/qml_features/build.rs
- examples/qml_features/src/main.cpp
- examples/qml_features/src/tests/myobject/tst_myobject.cpp
- examples/qml_features/src/tests/qttypes/tst_qttypes.cpp
- examples/qml_features/src/tests/serialisation/tst_serialisation.cpp
This will be removed from the build tool and instead later
this will be moved onto the macro.
For now just use cxx_qt as the default.
> cxx-qt-build: remove the option to specify a custom namespace prefix

- cxx-qt-gen/src/gen_cpp.rs
- cxx-qt-gen/test_outputs/invokables.cpp
- cxx-qt-gen/test_outputs/signals.cpp
- cxx-qt-gen/test_outputs/types_qt_invokable.cpp
- cxx-qt-lib/include/qt_types.h
This simplifies generation later as we don't need to generate
code to convert between the types, we only need to write the
input and output types.
> cxx-qt-lib: use generic templated method for converting returns

- cxx-qt-gen/src/extract.rs
- cxx-qt-gen/src/gen_rs.rs
- cxx-qt-gen/test_inputs/passthrough.rs
- cxx-qt-gen/test_outputs/passthrough.rs
Later we will pass through all non CXX-Qt items to the CXX bridge,
but this is a stepping stone that allows us to progress.
> gen_rs: pass through ForeignMod to the CXX bridge for now

- cxx-qt-build/Cargo.toml
- cxx-qt-build/src/lib.rs
- cxx-qt-gen/src/extract.rs
- cxx-qt-gen/src/gen_cpp.rs
- cxx-qt-gen/src/gen_rs.rs
- cxx-qt-gen/src/lib.rs
- cxx-qt-gen/src/syntax/mod.rs
- cxx-qt-gen/src/syntax/qtfile.rs
- cxx-qt-gen/src/syntax/qtitem.rs
- cxx-qt/src/lib.rs
This starts to split up the roles, later there will be more things
in syntax and other separate folders.
> cxx-qt-gen: start a new syntax folder to help processing syntax

- cxx-qt-gen/src/extract.rs
- cxx-qt-gen/src/gen_cpp.rs
- cxx-qt-gen/src/gen_rs.rs
- cxx-qt-gen/test_outputs/custom_default.rs
- cxx-qt-gen/test_outputs/handlers.h
- cxx-qt-gen/test_outputs/handlers.rs
- cxx-qt-gen/test_outputs/invokables.h
- cxx-qt-gen/test_outputs/invokables.rs
- cxx-qt-gen/test_outputs/naming.h
- cxx-qt-gen/test_outputs/naming.rs
- cxx-qt-gen/test_outputs/passthrough.rs
- cxx-qt-gen/test_outputs/properties.h
- cxx-qt-gen/test_outputs/properties.rs
- cxx-qt-gen/test_outputs/signals.h
- cxx-qt-gen/test_outputs/signals.rs
- cxx-qt-gen/test_outputs/types_primitive_property.h
- cxx-qt-gen/test_outputs/types_primitive_property.rs
- cxx-qt-gen/test_outputs/types_qt_invokable.h
- cxx-qt-gen/test_outputs/types_qt_invokable.rs
- cxx-qt-gen/test_outputs/types_qt_property.h
- cxx-qt-gen/test_outputs/types_qt_property.rs
This helps later to avoid collisions in C++ with RustObj, when the
CXX bridge can be used it is more explicit which type is being used,
and generally makes it more obvious which type is being referred to.
> cxx-qt-gen: have MyObjectRust on C++ side and MyObjectQt on Rust

- book/src/qobject/signals_enum.md
- cxx-qt-gen/src/extract.rs
- cxx-qt-gen/src/gen_rs.rs
- cxx-qt-gen/test_inputs/signals.rs
- cxx-qt-gen/test_outputs/signals.rs
- cxx-qt/src/lib.rs
- examples/qml_features/src/mock_qt_types.rs
- examples/qml_features/src/signals.rs
This allows us later to pick which QObject signals refer to and
easily allows us to determine which blocks are cxx_qt and which
are for CXX.
> cxx-qt-gen: use cxx_qt::signals attribute to define signals

- .github/workflows/github-cxx-qt-tests.yml
- CMakeLists.txt
- cmake/CxxQt.cmake
- cxx-qt-build/src/lib.rs
- cxx-qt-lib/Cargo.toml
- cxx-qt-lib/build.rs
- cxx-qt-lib/src/lib.rs
- cxx-qt-lib/src/qt_types.cpp
- qt-build/Cargo.toml
- qt-build/src/lib.rs
as [proposed](https://github.com/KDAB/cxx-qt/pull/173#issuecomment-1193353750)
> build cxx-qt-lib autogenerated C++ with Cargo instead of CMake

- README.md
- cxx-qt-gen/src/gen_rs.rs
- cxx-qt-gen/test_inputs/handlers.rs
- cxx-qt-gen/test_inputs/invokables.rs
- cxx-qt-gen/test_inputs/properties.rs
- cxx-qt-gen/test_inputs/signals.rs
- cxx-qt-gen/test_inputs/types_qt_invokable.rs
- cxx-qt-gen/test_inputs/types_qt_property.rs
- cxx-qt-gen/test_outputs/custom_default.rs
- cxx-qt-gen/test_outputs/handlers.rs
- cxx-qt-gen/test_outputs/invokables.rs
- cxx-qt-gen/test_outputs/naming.rs
- cxx-qt-gen/test_outputs/passthrough.rs
- cxx-qt-gen/test_outputs/properties.rs
- cxx-qt-gen/test_outputs/signals.rs
- cxx-qt-gen/test_outputs/types_primitive_property.rs
- cxx-qt-gen/test_outputs/types_qt_invokable.rs
- cxx-qt-gen/test_outputs/types_qt_property.rs
- examples/qml_extension_plugin/core/src/lib.rs
- examples/qml_features/src/lib.rs
- examples/qml_features/src/mock_qt_types.rs
- examples/qml_features/src/serialisation.rs
- examples/qml_features/src/signals.rs
- examples/qml_features/src/sub.rs
- examples/qml_features/src/types.rs
- examples/qml_minimal/src/lib.rs
- examples/qml_with_threaded_logic/src/lib.rs
- tests/basic_cxx_qt/src/data.rs
- tests/basic_cxx_qt/src/lib.rs
- tests/basic_cxx_qt/src/sub.rs
> cxx-qt-gen: use extern "C++" block to define Qt lib types

- cxx-qt-lib/include/qt_types.h
- cxx-qt-lib/src/qt_types.cpp
- cxx-qt-lib/src/types/qvariant.rs
- examples/qml_features/src/mock_qt_types.rs
- examples/qml_features/src/tests/qttypes/tst_qttypes.qml
- tests/qt_types_standalone/src/lib.rs
- tests/qt_types_standalone/src/main.cpp
For now we require users to invoke the Utf8 to Utf16 translation.
Requires #166
> cxx-qt-lib: use QString instead of String for QVariant

- cxx-qt-gen/src/gen_cpp.rs
- cxx-qt-gen/src/gen_rs.rs
- cxx-qt-gen/test_outputs/custom_default.rs
- cxx-qt-gen/test_outputs/handlers.cpp
- cxx-qt-gen/test_outputs/handlers.h
- cxx-qt-gen/test_outputs/handlers.rs
- cxx-qt-gen/test_outputs/invokables.cpp
- cxx-qt-gen/test_outputs/invokables.h
- cxx-qt-gen/test_outputs/invokables.rs
- cxx-qt-gen/test_outputs/naming.cpp
- cxx-qt-gen/test_outputs/naming.h
- cxx-qt-gen/test_outputs/naming.rs
- cxx-qt-gen/test_outputs/passthrough.rs
- cxx-qt-gen/test_outputs/properties.cpp
- cxx-qt-gen/test_outputs/properties.h
- cxx-qt-gen/test_outputs/properties.rs
- cxx-qt-gen/test_outputs/signals.cpp
- cxx-qt-gen/test_outputs/signals.h
- cxx-qt-gen/test_outputs/signals.rs
- cxx-qt-gen/test_outputs/types_primitive_property.cpp
- cxx-qt-gen/test_outputs/types_primitive_property.h
- cxx-qt-gen/test_outputs/types_primitive_property.rs
- cxx-qt-gen/test_outputs/types_qt_invokable.cpp
- cxx-qt-gen/test_outputs/types_qt_invokable.h
- cxx-qt-gen/test_outputs/types_qt_invokable.rs
- cxx-qt-gen/test_outputs/types_qt_property.cpp
- cxx-qt-gen/test_outputs/types_qt_property.h
- cxx-qt-gen/test_outputs/types_qt_property.rs
This helps later when invokables use a pointer to the C++ object
rather than the Rust object, as then they can use self.rust().prop
or unsafe { self.as_mut().rust_mut().prop = value; } etc.
There will also be helpers implemented onto the C++ object so that
for normal usecases they use set_prop and get_prop etc.
> cxx-qt-gen: add rust getters for immutable and mutable access

- README.md
- book/src/getting-started/1-qobjects-in-rust.md
- book/src/qobject/cpp_object.md
- book/src/qobject/rustobj_struct.md
- cxx-qt-gen/src/extract.rs
- cxx-qt-gen/src/gen_rs.rs
- cxx-qt-gen/test_inputs/invokables.rs
- cxx-qt-gen/test_inputs/naming.rs
- cxx-qt-gen/test_inputs/signals.rs
- cxx-qt-gen/test_inputs/types_qt_invokable.rs
- cxx-qt-gen/test_outputs/invokables.rs
- cxx-qt/src/lib.rs
- examples/demo_threading/src/lib.rs
- examples/qml_extension_plugin/core/src/lib.rs
- examples/qml_features/src/lib.rs
- examples/qml_features/src/mock_qt_types.rs
- examples/qml_features/src/nested.rs
- examples/qml_features/src/rust_obj_invokables.rs
- examples/qml_features/src/serialisation.rs
- examples/qml_features/src/signals.rs
- examples/qml_features/src/sub.rs
- examples/qml_features/src/types.rs
- examples/qml_minimal/src/lib.rs
- examples/qml_with_threaded_logic/src/lib.rs
- tests/basic_cxx_qt/src/data.rs
- tests/basic_cxx_qt/src/lib.rs
- tests/basic_cxx_qt/src/sub.rs
This helps later as the invokables are implemented onto a different
struct, so this clearly defines the split between C++ and Rust
methods etc.
> cxx-qt-gen: use impl cxx_qt::QObject<T> block for invokables

- cxx-qt-gen/Cargo.toml
- cxx-qt-gen/src/gen_cpp.rs
- cxx-qt-gen/src/gen_rs.rs
Enables proper multi-line diffing.
Before:
After:
Need I say more? ;)
> Use assert_str_eq! for file comparisons

- .github/workflows/github-cxx-qt-tests.yml
Should free up some MacOS runners.
> Auto-cancel previous workflows for the same PR.

- cxx-qt-gen/src/extract.rs
- cxx-qt-gen/src/gen_rs.rs
- cxx-qt-gen/src/parser/mod.rs
- cxx-qt-gen/src/parser/qobject.rs
- cxx-qt-gen/src/syntax/attribute.rs
- cxx-qt-gen/src/syntax/qtitem.rs
- cxx-qt-gen/test_inputs/custom_default.rs
- cxx-qt-gen/test_inputs/handlers.rs
- cxx-qt-gen/test_inputs/invokables.rs
- cxx-qt-gen/test_inputs/naming.rs
- cxx-qt-gen/test_inputs/properties.rs
- cxx-qt-gen/test_inputs/signals.rs
- cxx-qt-gen/test_inputs/types_primitive_property.rs
- cxx-qt-gen/test_inputs/types_qt_invokable.rs
- cxx-qt-gen/test_inputs/types_qt_property.rs
- cxx-qt/src/lib.rs
This allows us to process the namespace later and means we don't need
to remove the macro sometimes in the generation.
> cxx-qt-gen: remove the cxx_qt::bridge in the parser

- cxx-qt-gen/src/parser/cxxqtdata.rs
- cxx-qt-gen/src/parser/mod.rs
- cxx-qt-gen/src/parser/property.rs
- cxx-qt-gen/src/parser/qobject.rs
- cxx-qt-gen/src/parser/signals.rs
- cxx-qt-gen/src/syntax/fields.rs
Later when Data and RustObj structs are merged, properties will
be defined on the RustObj struct. This adds support for finding
these properties in the parser phase.
> cxx-qt-gen: parse any #[property] attributes on struct fields

- cxx-qt-gen/src/writer/cpp/header.rs
- cxx-qt-gen/src/writer/cpp/mod.rs
- cxx-qt-gen/src/writer/cpp/source.rs
- cxx-qt-gen/test_outputs/handlers.cpp
- cxx-qt-gen/test_outputs/handlers.h
- cxx-qt-gen/test_outputs/invokables.cpp
- cxx-qt-gen/test_outputs/invokables.h
- cxx-qt-gen/test_outputs/naming.cpp
- cxx-qt-gen/test_outputs/naming.h
- cxx-qt-gen/test_outputs/properties.cpp
- cxx-qt-gen/test_outputs/properties.h
- cxx-qt-gen/test_outputs/signals.cpp
- cxx-qt-gen/test_outputs/signals.h
- cxx-qt-gen/test_outputs/types_primitive_property.cpp
- cxx-qt-gen/test_outputs/types_primitive_property.h
- cxx-qt-gen/test_outputs/types_qt_invokable.cpp
- cxx-qt-gen/test_outputs/types_qt_invokable.h
- cxx-qt-gen/test_outputs/types_qt_property.cpp
- cxx-qt-gen/test_outputs/types_qt_property.h
> cxx-qt-gen: remove CppObj type alias from C++ side

- cxx-qt-gen/src/gen_rs.rs
- cxx-qt-gen/src/writer/cpp/header.rs
- cxx-qt-gen/src/writer/cpp/mod.rs
- cxx-qt-gen/src/writer/cpp/source.rs
- cxx-qt-gen/test_outputs/custom_default.rs
- cxx-qt-gen/test_outputs/handlers.cpp
- cxx-qt-gen/test_outputs/handlers.h
- cxx-qt-gen/test_outputs/handlers.rs
- cxx-qt-gen/test_outputs/invokables.cpp
- cxx-qt-gen/test_outputs/invokables.h
- cxx-qt-gen/test_outputs/invokables.rs
- cxx-qt-gen/test_outputs/naming.cpp
- cxx-qt-gen/test_outputs/naming.h
- cxx-qt-gen/test_outputs/naming.rs
- cxx-qt-gen/test_outputs/passthrough.rs
- cxx-qt-gen/test_outputs/properties.cpp
- cxx-qt-gen/test_outputs/properties.h
- cxx-qt-gen/test_outputs/properties.rs
- cxx-qt-gen/test_outputs/signals.cpp
- cxx-qt-gen/test_outputs/signals.h
- cxx-qt-gen/test_outputs/signals.rs
- cxx-qt-gen/test_outputs/types_primitive_property.cpp
- cxx-qt-gen/test_outputs/types_primitive_property.h
- cxx-qt-gen/test_outputs/types_primitive_property.rs
- cxx-qt-gen/test_outputs/types_qt_invokable.cpp
- cxx-qt-gen/test_outputs/types_qt_invokable.h
- cxx-qt-gen/test_outputs/types_qt_invokable.rs
- cxx-qt-gen/test_outputs/types_qt_property.cpp
- cxx-qt-gen/test_outputs/types_qt_property.h
- cxx-qt-gen/test_outputs/types_qt_property.rs
> cxx-qt-gen: fix rust getters in C++ to use camelcase

- cxx-qt-gen/Cargo.toml
- cxx-qt-gen/src/extract.rs
- cxx-qt-gen/src/gen_cpp.rs
- cxx-qt-gen/src/gen_rs.rs
- cxx-qt-gen/src/generator/mod.rs
- cxx-qt-gen/src/generator/naming/invokable.rs
- cxx-qt-gen/src/generator/naming/mod.rs
- cxx-qt-gen/src/generator/naming/module.rs
- cxx-qt-gen/src/generator/naming/namespace.rs
- cxx-qt-gen/src/generator/naming/property.rs
- cxx-qt-gen/src/generator/naming/qobject.rs
- cxx-qt-gen/src/generator/naming/signals.rs
- cxx-qt-gen/src/parser/property.rs
- cxx-qt-gen/src/parser/qobject.rs
This will handle taking the Parser components and then generating
the C++ or Rust idents from them.
> cxx-qt-gen: add a naming module to the generator phase

- crates/cxx-qt-gen/src/writer/rust/mod.rs
- crates/cxx-qt-gen/test_outputs/custom_default.rs
- crates/cxx-qt-gen/test_outputs/invokables.rs
- crates/cxx-qt-gen/test_outputs/naming.rs
- crates/cxx-qt-gen/test_outputs/passthrough.rs
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-gen/test_outputs/signals.rs
- crates/cxx-qt-gen/test_outputs/types_primitive_property.rs
- crates/cxx-qt-gen/test_outputs/types_qt_invokable.rs
- crates/cxx-qt-gen/test_outputs/types_qt_property.rs
We need to do this to avoid collisions when there are multiple QObjects
> cxx-qt-gen: mangle free rust functions names in writer

- crates/cxx-qt-gen/src/extract.rs
- crates/cxx-qt-gen/src/gen_rs.rs
- crates/cxx-qt-gen/src/generator/rust/mod.rs
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/src/writer/rust/mod.rs
- crates/cxx-qt-gen/test_outputs/custom_default.rs
- crates/cxx-qt-gen/test_outputs/invokables.rs
- crates/cxx-qt-gen/test_outputs/naming.rs
- crates/cxx-qt-gen/test_outputs/passthrough.rs
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-gen/test_outputs/signals.rs
- crates/cxx-qt-gen/test_outputs/types_primitive_property.rs
- crates/cxx-qt-gen/test_outputs/types_qt_invokable.rs
- crates/cxx-qt-gen/test_outputs/types_qt_property.rs
> cxx-qt-gen: add support for multiple qobjects in rust writer

- crates/cxx-qt-gen/src/extract.rs
- crates/cxx-qt-gen/src/gen_rs.rs
- crates/cxx-qt-gen/src/generator/cpp/invokable.rs
- crates/cxx-qt-gen/src/generator/naming/invokable.rs
- crates/cxx-qt-gen/src/generator/rust/mod.rs
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/src/parser/invokable.rs
- crates/cxx-qt-gen/src/parser/qobject.rs
- crates/cxx-qt-gen/src/syntax/implitemmethod.rs
- crates/cxx-qt-gen/src/syntax/mod.rs
- crates/cxx-qt-gen/src/writer/rust/mod.rs
- crates/cxx-qt-gen/test_outputs/custom_default.rs
- crates/cxx-qt-gen/test_outputs/invokables.rs
- crates/cxx-qt-gen/test_outputs/naming.rs
- crates/cxx-qt-gen/test_outputs/passthrough.rs
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-gen/test_outputs/signals.rs
- crates/cxx-qt-gen/test_outputs/types_primitive_property.rs
- crates/cxx-qt-gen/test_outputs/types_qt_invokable.rs
- crates/cxx-qt-gen/test_outputs/types_qt_property.rs
This has various commits which help the new Rust generation later, but can be landed separately.
> cxx-qt-gen: prepare for gen_rs removal and generating rust

- crates/cxx-qt-gen/src/generator/naming/namespace.rs
- crates/cxx-qt-gen/src/generator/naming/qobject.rs
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
- crates/cxx-qt-gen/src/parser/mod.rs
- crates/cxx-qt-gen/src/parser/qobject.rs
The qobject_struct is not optional so change the parser to remove the Option<T>
> cxx-qt-gen: change qobject struct to not be optional in Parser

- crates/qt-build/src/lib.rs
so the warnings show up with `cargo build -vv`
https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargo-warning
> qt-build: use println!("cargo:warning") instead of eprintln!

- crates/cxx-qt-gen/src/generator/rust/field.rs
- crates/cxx-qt-gen/src/generator/rust/mod.rs
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/src/parser/property.rs
- crates/cxx-qt-gen/src/parser/qobject.rs
- crates/cxx-qt-gen/test_inputs/properties.rs
- crates/cxx-qt-gen/test_outputs/properties.rs
- examples/demo_threading/rust/src/lib.rs
- tests/basic_cxx_qt/cpp/main.cpp
- tests/basic_cxx_qt/rust/src/lib.rs
Note that the prop_mut is not unsafe as there is no signal that should be emitted.
Requires #267
> cxx-qt-gen: add prop/prop_mut/set_prop for Rust fields as well

- crates/cxx-qt-gen/src/generator/cpp/invokable.rs
- crates/cxx-qt-gen/src/generator/cpp/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/property/mod.rs
- crates/cxx-qt-gen/src/writer/cpp/header.rs
- crates/cxx-qt-gen/src/writer/cpp/mod.rs
- crates/cxx-qt-gen/src/writer/cpp/source.rs
- crates/cxx-qt-gen/test_outputs/invokables.cpp
- crates/cxx-qt-gen/test_outputs/invokables.h
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.cpp
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.h
- crates/cxx-qt-gen/test_outputs/properties.cpp
- crates/cxx-qt-gen/test_outputs/properties.h
- crates/cxx-qt-gen/test_outputs/signals.cpp
- crates/cxx-qt-gen/test_outputs/signals.h
- crates/cxx-qt-lib-headers/include/cxxqt_thread.h
This then allows for methods to trigger signals which are linked on the same thread to invokables.
eg beginInsertRows triggers rowCount().
This is safe because to emit a signal you need a mutable self, which then allows other methods to be called with similar rules in Rust around ownership. And we still protect against other threads from calling the RustObj at the same time.
We also still have queued signals as the "safe" route for now, to ensure that slots are called "later". Obvious C++ code can be written to call on a different thread and cause a deadlock from a method in the base class being called.
> cxx-qt-gen: use recursive mutex for rust object

- crates/cxx-qt-lib-headers/include/qcolor.h
- crates/cxx-qt-lib-headers/include/qdatetime.h
- crates/cxx-qt-lib-headers/include/qstring.h
- crates/cxx-qt-lib-headers/include/qurl.h
- crates/cxx-qt-lib-headers/include/qvariant.h
- crates/cxx-qt-lib/build.rs
- crates/cxx-qt-lib/src/types/assertion_utils.h
- crates/cxx-qt-lib/src/types/qcolor.cpp
- crates/cxx-qt-lib/src/types/qdate.cpp
- crates/cxx-qt-lib/src/types/qdatetime.cpp
- crates/cxx-qt-lib/src/types/qpoint.cpp
- crates/cxx-qt-lib/src/types/qpointf.cpp
- crates/cxx-qt-lib/src/types/qrect.cpp
- crates/cxx-qt-lib/src/types/qrectf.cpp
- crates/cxx-qt-lib/src/types/qsize.cpp
- crates/cxx-qt-lib/src/types/qsizef.cpp
- crates/cxx-qt-lib/src/types/qstring.cpp
- crates/cxx-qt-lib/src/types/qtime.cpp
- crates/cxx-qt-lib/src/types/qurl.cpp
- crates/cxx-qt-lib/src/types/qvariant.cpp
Also splits up the qt_types.h / qt_types.cpp into individual files for the different types.
> Assert qt type layouts

- book/src/qobject/qobject_struct.md
- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
- crates/cxx-qt-gen/src/parser/qobject.rs
- crates/cxx-qt-gen/src/syntax/path.rs
- crates/cxx-qt-gen/src/writer/rust/mod.rs
- crates/cxx-qt-gen/test_inputs/invokables.rs
- crates/cxx-qt-gen/test_inputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_inputs/signals.rs
- crates/cxx-qt-gen/test_outputs/invokables.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-gen/test_outputs/signals.rs
- crates/cxx-qt/src/lib.rs
- examples/demo_threading/rust/src/lib.rs
- examples/qml_extension_plugin/plugin/rust/src/lib.rs
- examples/qml_features/rust/src/custom_base.rs
- examples/qml_features/rust/src/lib.rs
- examples/qml_features/rust/src/mock_qt_types.rs
- examples/qml_features/rust/src/rust_obj_invokables.rs
- examples/qml_features/rust/src/serialisation.rs
- examples/qml_features/rust/src/signals.rs
- examples/qml_features/rust/src/threading.rs
- examples/qml_features/rust/src/types.rs
- examples/qml_minimal/rust/src/cxxqt_object.rs
- tests/basic_cxx_qt/rust/src/data.rs
- tests/basic_cxx_qt/rust/src/lib.rs
This then creates a natural way to add methods to the C++ context.
It also means later with nested objects they can be referred to by crates::module::qobject::MyObject.
And any Rust traits or methods are natural as they are impl A for T, with traits for the C++ object being natural with impl A for qobject::T
> cxx-qt-gen: use impl qobject::T to define the C++ context

- crates/cxx-qt-gen/src/generator/rust/signals.rs
- crates/cxx-qt-gen/test_inputs/signals.rs
- crates/cxx-qt-gen/test_outputs/signals.cpp
- crates/cxx-qt-gen/test_outputs/signals.h
- crates/cxx-qt-gen/test_outputs/signals.rs
- examples/qml_features/rust/src/signals.rs
As the lifetime will be the lifetime of the enum. Then we don't need this in the CXX method as it can be inferred.
> cxx-qt-gen: strip lifetimes from CXX definitions for signals

- book/src/qobject/signals_enum.md
- crates/cxx-qt-gen/src/generator/rust/signals.rs
- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
- crates/cxx-qt-gen/src/parser/mod.rs
- crates/cxx-qt-gen/src/parser/signals.rs
- crates/cxx-qt-gen/src/syntax/attribute.rs
- crates/cxx-qt-gen/test_inputs/signals.rs
- crates/cxx-qt/src/lib.rs
- examples/qml_features/rust/src/serialisation.rs
- examples/qml_features/rust/src/signals.rs
This then matches the Qt Q_SIGNALS closer and is consistent with qproperty and qinvokable etc.
> cxx-qt-gen: rename cxx_qt::signals to cxx_qt::qsignals

- examples/cargo_without_cmake/build.rs
Otherwise we have unused warnings from the compiler on Windows
> cargo_without_cmake: mark unix only method as such

- book/src/concepts/threading.md
- crates/cxx-qt-gen/src/generator/naming/qobject.rs
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/src/writer/rust/mod.rs
- crates/cxx-qt-gen/test_outputs/invokables.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-gen/test_outputs/signals.rs
- crates/cxx-qt-lib-headers/include/cxxqt_thread.h
- examples/demo_threading/rust/src/lib.rs
- examples/qml_features/rust/src/threading.rs
The idea is to pass a `(callback fn, Send + 'static closure)` pair in to
`QMetaObject::invokeMethod()`, and invoke the callback fn with that closure
as an argument. The callback fn just invokes the passed closure. This way,
we can queue Rust closure back to QObject thread.
thread::spawn(move || {
...
let response = String::new();
qt_thread.queue(move |qobject| qobject.emit(Finished { response }));
});
This should be simpler and less error-prone than sending result back via
a separate channel.
> cxx-qt-gen: wrap CxxQtThread::queue() to support Send + 'static closure

- crates/cxx-qt-build/Cargo.toml
- crates/cxx-qt-gen/Cargo.toml
- examples/demo_threading/rust/Cargo.toml
As per the cargo docs, any versions that are less than 1.0 need bumping a minor version to move to the next series (after 1.0 it's the major version that needs bumping). So bump `convert_case` 0.4 -> 0.6 and `uuid` 0.8 -> 1.2.
```
1.2.3  :=  >=1.2.3, <2.0.0
1.2    :=  >=1.2.0, <2.0.0
1      :=  >=1.0.0, <2.0.0
0.2.3  :=  >=0.2.3, <0.3.0
0.2    :=  >=0.2.0, <0.3.0
0.0.3  :=  >=0.0.3, <0.0.4
0.0    :=  >=0.0.0, <0.1.0
0      :=  >=0.0.0, <1.0.0
```
https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio
> cargo: bump convert_case and uuid as they are below 1.0

- crates/cxx-qt-build/src/lib.rs
- crates/cxx-qt-gen/src/lib.rs
- crates/qt-build-utils/src/lib.rs
Resolves the warning:
The borrowed expression implements the required traits
> clippy: fix new 1.65 warnings

- CHANGELOG.md
- crates/qt-build-utils/src/lib.rs
The CI changes are only for testing this branch; I'll remove those before merging so we don't have 2 more CI jobs to wait on.
> support linking Qt as macOS framework

- crates/cxx-qt-build/src/lib.rs
- crates/cxx-qt-gen/src/generator/cpp/fragment.rs
- crates/cxx-qt-gen/src/generator/cpp/invokable.rs
- crates/cxx-qt-gen/src/generator/cpp/property/getter.rs
- crates/cxx-qt-gen/src/generator/cpp/property/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/property/setter.rs
- crates/cxx-qt-gen/src/generator/cpp/property/signal.rs
- crates/cxx-qt-gen/src/generator/cpp/qobject.rs
- crates/cxx-qt-gen/src/generator/cpp/signal.rs
- crates/cxx-qt-gen/src/lib.rs
- crates/cxx-qt-gen/src/writer/cpp/header.rs
- crates/cxx-qt-gen/src/writer/cpp/mod.rs
- crates/cxx-qt-gen/src/writer/cpp/source.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.cpp
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.h
- crates/cxx-qt-gen/test_outputs/properties.cpp
- crates/cxx-qt-gen/test_outputs/properties.h
- crates/cxx-qt-gen/test_outputs/signals.h
- crates/cxx-qt-lib-headers/src/lib.rs
- crates/cxx-qt-lib/build.rs
#332
Using `Q_SIGNAS` and `Q_SLOT` to tag `QObject` methods.
What's your opinion about having those methods grouped together?
e.g.
1
```
public:
int count() const;
bool toggle() const;
Q_INVOKABLE void invokable();
void cppMethod();
public:
Q_SLOT void setCount(int count);
Q_SLOT void setToggle(bool toggle);
public:
Q_SIGNAL void countChanged();
Q_SIGNAL void toggleChanged();
```
2
or having one group like `Q_INVOKABLE` is expected:
```
public:
int count() const;
bool toggle() const;
Q_INVOKABLE void invokable();
void cppMethod();
Q_SLOT void setCount(int count);
Q_SLOT void setToggle(bool toggle);
Q_SIGNAL void countChanged();
Q_SIGNAL void toggleChanged();
```
This PR provides 1 solution.
> #332 add `Q_SIGNAL` and `Q_SLOT` to methods definitions

- CHANGELOG.md
- crates/cxx-qt-gen/src/generator/cpp/types.rs
Related to #328 
This adds missing support in our generation for having `Pin<T>` as a type.
> cxx-qt-gen: generate C++ types for Pin<T> correctly

- crates/cxx-qt-build/src/lib.rs
- crates/cxx-qt-gen/src/generator/naming/invokable.rs
- crates/cxx-qt-gen/src/generator/naming/property.rs
- crates/cxx-qt-gen/src/generator/naming/qobject.rs
- crates/cxx-qt-gen/src/writer/rust/mod.rs
- crates/cxx-qt-lib-headers/include/common.h
- crates/cxx-qt-lib-headers/src/lib.rs
- crates/cxx-qt-lib/build.rs
- crates/cxx-qt-lib/src/types/qbytearray.rs
- crates/cxx-qt-lib/src/types/qcolor.rs
- crates/cxx-qt-lib/src/types/qdate.rs
- crates/cxx-qt-lib/src/types/qdatetime.rs
- crates/cxx-qt-lib/src/types/qmodelindex.rs
- crates/cxx-qt-lib/src/types/qpersistentmodelindex.rs
- crates/cxx-qt-lib/src/types/qpoint.rs
- crates/cxx-qt-lib/src/types/qpointf.rs
- crates/cxx-qt-lib/src/types/qrect.rs
- crates/cxx-qt-lib/src/types/qrectf.rs
- crates/cxx-qt-lib/src/types/qsize.rs
- crates/cxx-qt-lib/src/types/qsizef.rs
- crates/cxx-qt-lib/src/types/qstring.rs
- crates/cxx-qt-lib/src/types/qstringlist.rs
- crates/cxx-qt-lib/src/types/qtime.rs
- crates/cxx-qt-lib/src/types/qurl.rs
- crates/cxx-qt-lib/src/types/qvector2d.rs
- crates/cxx-qt-lib/src/types/qvector3d.rs
- crates/cxx-qt-lib/src/types/qvector4d.rs
- crates/cxx-qt/src/lib.rs
- crates/qt-build-utils/src/lib.rs
- examples/qml_features/rust/src/containers.rs
This completes the second item of #53.
Fixes #369
For some types I have implemented particularly fancy pretty printing, for example `QColor` **actually** prints the color via terminal escape codes, please let me know if that is "too fancy":
> cxx-qt-lib: Implement Debug+Display for all basic types

- crates/cxx-qt-gen/src/generator/rust/property/mod.rs
- crates/cxx-qt-gen/src/generator/rust/property/setter.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-lib-headers/include/common.h
- crates/cxx-qt-lib/src/core/qbytearray.rs
- crates/cxx-qt-lib/src/core/qdate.rs
- crates/cxx-qt-lib/src/core/qdatetime.rs
- crates/cxx-qt-lib/src/core/qmodelindex.rs
- crates/cxx-qt-lib/src/core/qpersistentmodelindex.rs
- crates/cxx-qt-lib/src/core/qpoint.rs
- crates/cxx-qt-lib/src/core/qpointf.rs
- crates/cxx-qt-lib/src/core/qrect.rs
- crates/cxx-qt-lib/src/core/qrectf.rs
- crates/cxx-qt-lib/src/core/qsize.rs
- crates/cxx-qt-lib/src/core/qsizef.rs
- crates/cxx-qt-lib/src/core/qstring.rs
- crates/cxx-qt-lib/src/core/qstringlist.rs
- crates/cxx-qt-lib/src/core/qtime.rs
- crates/cxx-qt-lib/src/core/qurl.rs
- crates/cxx-qt-lib/src/gui/qcolor.rs
- crates/cxx-qt-lib/src/gui/qvector2d.rs
- crates/cxx-qt-lib/src/gui/qvector3d.rs
- crates/cxx-qt-lib/src/gui/qvector4d.rs
- examples/qml_features/tests/tst_containers.qml
- examples/qml_features/tests/tst_properties.qml
This also allows us to trigger `changed()` signals only when the value really changed.
After this we can also implement std::cmp::PartialOrd for selected types, but it does not make sense for all types (e.g. not for `QByteArray`)
See #53
> Implement std::cmp::PartialEq for all Qt types

- crates/cxx-qt-gen/src/generator/cpp/types.rs
- crates/cxx-qt-gen/src/lib.rs
- crates/cxx-qt-lib-headers/src/lib.rs
- crates/cxx-qt-lib/src/core/qbytearray.rs
- crates/cxx-qt-lib/src/core/qlist/mod.rs
- crates/cxx-qt-lib/src/core/qset/mod.rs
- crates/cxx-qt-lib/src/core/qvector/mod.rs
- crates/qt-build-utils/src/lib.rs
- examples/qml_minimal/rust/src/cxxqt_object.rs
- tests/basic_cxx_qt/rust/src/lib.rs
Another one for #53
As discussed, `Ord` probably doesn't make much sense for container types, but `Eq` does (as long as the element types are `Eq` as well).
> Implement {PartialEq,Eq} for container types

- README.md
Fixes https://github.com/KDAB/cxx-qt/issues/426
> README: explain how to enable symlinks on Windows 10

- crates/cxx-qt-lib/src/core/qhash/mod.rs
- crates/cxx-qt-lib/src/core/qmap/mod.rs
This is a small addendum to #423, where map types were left out by accident.
ref: #53
> Implement equality for map types

- CMakeLists.txt
- README.md
- examples/demo_threading/CMakeLists.txt
- examples/qml_extension_plugin/CMakeLists.txt
- examples/qml_features/CMakeLists.txt
- examples/qml_minimal/CMakeLists.txt
- tests/basic_cxx_only/CMakeLists.txt
- tests/basic_cxx_qt/CMakeLists.txt
- tests/qt_types_standalone/CMakeLists.txt
required for linking with WHOLE_ARCHIVE
https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html?highlight=whole_archive#genex:LINK_LIBRARY
https://github.com/KDAB/cxx-qt/issues/442
> set minimum CMake version to 3.24

- CHANGELOG.md
- crates/cxx-qt-lib/src/core/qmodelindex.cpp
- crates/cxx-qt-lib/src/core/qmodelindex.rs
- crates/cxx-qt-lib/src/core/qvariant/mod.rs
- crates/cxx-qt-lib/src/core/qvariant/qvariant.cpp
- crates/cxx-qt-lib/src/gui/qcolor.cpp
- crates/cxx-qt-lib/src/gui/qcolor.rs
> cxx-qt-lib: ensure correct sizes for wasm 32bit

- CHANGELOG.md
- crates/cxx-qt/src/lib.rs
This improve error messages when our cxx-qt-gen code breaks.
Eg I have added a duplicate attribute key-value in the code, before we used to get this error when compiling.
```
error: custom attribute panicked
--> examples/cargo_without_cmake/src/cxxqt_object.rs:11:1
|
11 | #[cxx_qt::bridge]
| ^^^^^^^^^^^^^^^^^
|
= help: message: called `Result::unwrap()` on an `Err` value: Error("Duplicate keys in the attributes")
```
Now we have a much better error that points to the code block that is at fault.
```
error: Duplicate keys in the attributes
--> examples/cargo_without_cmake/src/cxxqt_object.rs:23:5
|
23 |     #[cxx_qt::qobject(qml_uri = "com.kdab.cxx_qt.demo", qml_version = "1.0", qml_version = "1.0")]
|     ^
```
Related to #38
> cxx-qt: don't use unwrap and convert to a compile error instead

- CHANGELOG.md
- crates/cxx-qt-lib-headers/include/common.h
- crates/cxx-qt-lib-headers/include/core/qstring.h
- crates/cxx-qt-lib/src/core/qmargins.rs
- crates/cxx-qt-lib/src/core/qmarginsf.rs
- crates/cxx-qt-lib/src/core/qpoint.rs
- crates/cxx-qt-lib/src/core/qpointf.rs
- crates/cxx-qt-lib/src/core/qrect.rs
- crates/cxx-qt-lib/src/core/qrectf.rs
- crates/cxx-qt-lib/src/core/qsize.rs
- crates/cxx-qt-lib/src/core/qsizef.rs
- crates/cxx-qt-lib/src/core/qstring.cpp
- crates/cxx-qt-lib/src/core/qstring.rs
- crates/cxx-qt-lib/src/gui/qvector2d.rs
- crates/cxx-qt-lib/src/gui/qvector3d.rs
- crates/cxx-qt-lib/src/gui/qvector4d.rs
I used the `derive_more` crate for some types, because it allows to derive these operators for simple types.
Let me know if you want to avoid adding this dependency.
Are there any more types, where an operator could be implemented?
ref: #53
> Implement std::ops for applicable Qt types

- crates/cxx-qt-gen/src/syntax/qtitem.rs
Before we needed to have #[allow(clippy::large_enum_variant)] otherwise when running clippy via a dependency, eg by running cxx-qt-build clippy or the whole workspace it would fail. Even though clippy would pass individually for cxx-qt-gen.
This now doesn't happen with the latest clippy version, so remove this workaround.
Closes #225
> cxx-qt-gen: remove clippy allow as it isn't required anymore

- crates/cxx-qt-gen/src/generator/cpp/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/qobject.rs
- crates/cxx-qt-gen/src/generator/rust/mod.rs
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
- crates/cxx-qt-gen/src/parser/mod.rs
- crates/cxx-qt-gen/src/parser/qobject.rs
Before this patch if you didn't mark a qobject struct as public the following error would occur.
```
[build] error[E0432]: unresolved import `super`
[build]   --> examples/qml_minimal/rust/src/cxxqt_object.rs:24:12
[build]    |
[build] 24 |     struct MyObject {
[build]    |            ^^^^^^^^ no `MyObject` in `cxxqt_object`
[build]    |
[build] help: consider importing this type alias instead
[build]    |
[build] 24 |     struct crate::cxxqt_object::qobject::MyObject;
[build]    |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
After this patch the error is explicit.
```
[build] error: qobject marked structs must be public
[build]   --> examples/qml_minimal/rust/src/cxxqt_object.rs:24:5
[build]    |
[build] 24 |     struct MyObject {
[build]    |     ^^^^^^
```
Closes #457
> cxx-qt-gen: have an explicit error for non public qobjects

- crates/cxx-qt-build/src/lib.rs
- crates/cxx-qt-lib-headers/src/lib.rs
- crates/cxx-qt/Cargo.toml
- crates/cxx-qt/src/lib.rs
> cxx-qt: activate doctests for the macros and deny missing docs in the crate

- .github/workflows/github-cxx-qt-tests.yml
This seems to fix the warning message:
```
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
Hopefully this will also fix CI rebuilding the world all the time.
> Bump actions/cache to v3

- CHANGELOG.md
- crates/cxx-qt-lib/Cargo.toml
- crates/cxx-qt-lib/src/core/qdate.rs
- crates/cxx-qt-lib/src/core/qdatetime.rs
- crates/cxx-qt-lib/src/core/qtime.rs
> cxx-qt-lib: Add chrono and time support for {QDate,QDateTime,QTime}

- .gitignore
- examples/qml_extension_plugin/tests/CMakeLists.txt
- examples/qml_extension_plugin/tests/main.cpp
- examples/qml_extension_plugin/tests/valgrind_additional_suppressions.txt
- examples/qml_extension_plugin/tests/valgrind_additional_suppressions.txt.license
Use QTest directly, this fixes the build on my Fedora machine, which only provides qmltestrunner linked with Qt5.
> Remove qmltestrunner dependency

- CHANGELOG.md
- Cargo.toml
This syncs back the changes from the `0.5.x` branch
> bump: release to 0.5.1 (sync back from `0.5.x` branch)

- README.md
It is stated that symlink should be enabled before cloning, but copying the current command from readme doesn't work if we are not in a repo.
```
> git config core.symlinks true
fatal: not in a git directory
```
Adding the --global flag write it in the user config.
> doc: add `--global` to `git config` when setting up symlink

- .github/workflows/github-cxx-qt-tests.yml
- crates/cxx-qt-gen/src/lib.rs
On windows sometime the generated file, or the value returned from the clang-format call get \r in them.
It is sane to remove all of them, to get consistency between unix and windows system for tests.
> cxx-qt-gen: fix test on windows (remove '\r')

- crates/cxx-qt-gen/src/syntax/qtfile.rs
Before, the missing file was not logged in the panic message, making it hard to debug.
I encountered this error while following the qml-minimal example, I did a typo in my build.rs. Being not familiar with build.rs, it was quite frustrating for me to find the source of the problem.
```
ompiling qml-minimal v0.1.0 (C:\Users\olivi\dev\cxx-qt-tutorial\rust)
error: failed to run custom build command for `qml-minimal v0.1.0 (C:\Users\olivi\dev\cxx-qt-tutorial\rust)`
Caused by:
process didn't exit successfully: `C:\Users\olivi\dev\cxx-qt-tutorial\rust\target\debug\build\qml-minimal-b0eab65f7e8191c2\build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=src/cxxqt_object_doesntexist.rs
cargo:rerun-if-env-changed=QMAKE
cargo:rerun-if-env-changed=QT_VERSION_MAJOR …
```
> cxx-qt-gen: Fix the format of the error when a file is not found

- README.md
It is two step:
- `cargo install mdbook`
- `cargo install mdbook-linkcheck`
So it should be 2 links.
> doc: separate mdbook & mdbook-linkcheck

- .github/workflows/github-cxx-qt-tests.yml
- CMakeLists.txt
- examples/qml_extension_plugin/tests/CMakeLists.txt
- examples/qml_features/CMakeLists.txt
- examples/qml_minimal/CMakeLists.txt
- tests/CMakeLists.txt
- tests/basic_cxx_only/cpp/cxx_test.cpp
- tests/basic_cxx_only/cpp/cxx_test.h
- tests/basic_cxx_only/cpp/main.cpp
- tests/basic_cxx_only/rust/build.rs
- tests/basic_cxx_only/rust/src/lib.rs
They were failing due to missing dll. This commit
- inject the location of Qt dll in the PATH
- Qt plugin directory in QT_PLUGIN_PATH
- Qml import path in QML_IMPORT_PATH & QML2_IMPORT_PATH
They are not necessary to every tests, but at least they should be robust for the future when more tests will be added.
This commit use `ENVIRONMENT_MODIFICATION` instead of `ENVIRONMENT`, since adding a value to the PATH in windows is a mess otherwise with CMake, because `;` is used as a list separator.
It also move `add_subdirectory` of book and example at the end of main CMakeLists.txt file, in order not to duplicate code to set `RUNTIME_ENV`.
Next step is to refactor all the `add_test` function in some helper function `add_cxxqt_test` or something like that.
fix #111
> tests: make tests run in CI on windows

- CMakeLists.txt
- tests/CMakeLists.txt
Continue effort from https://github.com/KDAB/cxx-qt/pull/243 now that CI work on windows.
- I've removed `WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}` since I'm not sure what it is for?
- I've fixed the `--target-dir` to work with multi config generator too.
> Cargo test workspace

- CHANGELOG.md
- crates/cxx-qt-build/src/lib.rs
- examples/cargo_without_cmake/build.rs
As it has no side affect for CMake builds, always call it so that developers don't need to know about this detail for Cargo builds.
Closes #508
> cxx-qt-build: always call qt_build_utils::setup_linker

- CMakeLists.txt
This appears to have been missed in
https://github.com/KDAB/cxx-qt/commit/048c7e9ab3bde427ed321044b4abed9e37f404a5
> ctest: ensure that cargo fmt is run across the workspace

- .github/workflows/book.yml
- .github/workflows/github-cxx-qt-tests.yml
This should prevent the cache increasing in size due to a cache per branch, which can cause the main cache to be removed.
> ci: only save compiler cache when the branch is main

- .github/workflows/github-cxx-qt-tests.yml
As this is from a push event / commit rather than a tag
where we need to inspect the base ref of the tag for the book.
> ci: use github.ref instead of github.event.base_ref for post cache

- CHANGELOG.md
- crates/cxx-qt-build/src/lib.rs
Otherwise the build fails with
link modifiers combination `+bundle,+whole-archive` is unstable when generating rlibs
Closes #519
> cxx-qt-build: unset bundle for link modifiers

- CHANGELOG.md
- Cargo.toml
This cherry-picks back the CHANGELOG and version updates for 0.5.2 into main
> bump: release to 0.5.2

- examples/cargo_without_cmake/CMakeLists.txt
- examples/demo_threading/CMakeLists.txt
- examples/qml_extension_plugin/plugin/CMakeLists.txt
- examples/qml_features/CMakeLists.txt
- examples/qml_minimal/CMakeLists.txt
This is a workaround until a bug is fixed upstream which breaks incremental builds in projects with multiple targets, causing very slow builds.
https://github.com/corrosion-rs/corrosion/issues/386
Related to #523
> cmake: use older corrosion version to fix incremental builds

- crates/cxx-qt-gen/src/generator/cpp/inherit.rs
- crates/cxx-qt-gen/src/generator/cpp/invokable.rs
- crates/cxx-qt-gen/src/generator/cpp/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/property/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/qobject.rs
- crates/cxx-qt-gen/src/generator/cpp/signal.rs
- crates/cxx-qt-gen/src/generator/cpp/types.rs
- crates/cxx-qt-gen/src/generator/naming/invokable.rs
- crates/cxx-qt-gen/src/generator/naming/property.rs
- crates/cxx-qt-gen/src/generator/rust/field.rs
- crates/cxx-qt-gen/src/generator/rust/inherit.rs
- crates/cxx-qt-gen/src/generator/rust/invokable.rs
- crates/cxx-qt-gen/src/generator/rust/mod.rs
- crates/cxx-qt-gen/src/generator/rust/property/mod.rs
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/src/generator/rust/signals.rs
- crates/cxx-qt-gen/src/generator/rust/types.rs
- crates/cxx-qt-gen/src/lib.rs
- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
- crates/cxx-qt-gen/src/parser/inherit.rs
- crates/cxx-qt-gen/src/parser/mod.rs
- crates/cxx-qt-gen/src/parser/qobject.rs
- crates/cxx-qt-gen/src/parser/signals.rs
- crates/cxx-qt-gen/src/syntax/attribute.rs
- crates/cxx-qt-gen/src/syntax/fields.rs
- crates/cxx-qt-gen/src/syntax/foreignmod.rs
- crates/cxx-qt-gen/src/syntax/implitemfn.rs
- crates/cxx-qt-gen/src/syntax/path.rs
- crates/cxx-qt-gen/src/syntax/types.rs
- crates/cxx-qt-gen/src/writer/rust/mod.rs
> cxx-qt-gen: remove tokens_to_syn and use parse_quote instead

- crates/cxx-qt-build/src/diagnostics.rs
- crates/cxx-qt-build/src/lib.rs
This allows for CXX errors to appear with a span in the macro expansion
Before this change if you had a unsupported type in an invokable only the following error would occur.
```
[build]   thread 'main' panicked at 'Could not generate C++ from Rust file:
Syn(Error("unsupported type: QUrl"))', crates/cxx-qt-build/src/lib.rs:120:14
```
Now with this change we have an additional error from the macro expansion.
```
[build] error: unsupported type: QUrl
[build]   --> examples/qml_minimal/rust/src/cxxqt_object.rs:57:35
[build]    |
[build] 57 |         pub fn test(&self, _url: &QUrl) {
[build]    |                                   ^^^^
```
Note however this does cause loads of extra errors below but this is a side effect of the rest of the CXX macro not being expanded, this first error is the …
> cxx-qt-build: do not panic for cxx_gen failures instead use Result

- CHANGELOG.md
- Cargo.toml
This is the sync back from the 0.5.x branch to main.
> bump: release to 0.5.3

- crates/cxx-qt-gen/Cargo.toml
- crates/cxx-qt-gen/src/lib.rs
- crates/cxx-qt-gen/test_outputs/inheritance.rs
- crates/cxx-qt-gen/test_outputs/invokables.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-gen/test_outputs/signals.rs
- crates/cxx-qt-gen/update_expected.sh
- crates/cxx-qt-lib/Cargo.toml
Use CXXQT_UPDATE_EXPECTED=/path/to/crates/cxx-qt-gen/ to update the test_outputs/ directory.
This is very useful for bulk updates when making changes to small cross-cutting concerns.
> Add ability to auto-update test_outputs/ directory

- crates/cxx-qt-gen/update_expected.sh
Otherwise all cargo projects in the cwd are built when this isn't required to update the expected.
> update_expected: ensure cwd is the cxx-qt-gen folder

- Cargo.toml
- crates/cxx-qt-build/src/diagnostics.rs
- examples/cargo_without_cmake/Cargo.toml
- examples/qml_minimal/rust/Cargo.toml
Output:
This still requires upstream changes, see:
https://github.com/dtolnay/cxx/pull/1214
> CXX errors: Expand and display span

- crates/cxx-qt-gen/src/writer/rust/mod.rs
- crates/cxx-qt-gen/test_outputs/inheritance.rs
- crates/cxx-qt-gen/test_outputs/invokables.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-gen/test_outputs/signals.rs
- crates/cxx-qt/src/lib.rs
This trait is automatically implemented on any `qobject::T`. It currently exposes the inner Rust type for a given QObject.
First step of implementing #550
This also requires us to split our macros into a cxx-qt-macro crate, as otherwise only exporting proc-macros is allowed.
We could now potentially move CxxQtThread into the cxx-qt crate now to remove the dependency on cxx-qt-lib.
> cxx-qt: Add CxxQtType trait

- CHANGELOG.md
- crates/cxx-qt-gen/src/writer/cpp/header.rs
- crates/cxx-qt-gen/src/writer/cpp/mod.rs
- crates/cxx-qt-gen/src/writer/cpp/source.rs
- crates/cxx-qt-gen/src/writer/rust/mod.rs
- crates/cxx-qt-gen/test_outputs/inheritance.cpp
- crates/cxx-qt-gen/test_outputs/inheritance.h
- crates/cxx-qt-gen/test_outputs/inheritance.rs
- crates/cxx-qt-gen/test_outputs/invokables.cpp
- crates/cxx-qt-gen/test_outputs/invokables.h
- crates/cxx-qt-gen/test_outputs/invokables.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.cpp
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.h
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.cpp
- crates/cxx-qt-gen/test_outputs/properties.h
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-gen/test_outputs/signals.cpp
- crates/cxx-qt-gen/test_outputs/signals.h
- crates/cxx-qt-gen/test_outputs/signals.rs
Will probably be readded as part of the Constructor trait later.
This wasn't documented anywhere and isn't used by anything at the moment.
> Remove newCppObject method for now.

- crates/cxx-qt-gen/src/lib.rs
Now new generated code is marked green and removed code is marked red.
> cxx-qt-gen: Fix diff order

- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
- crates/cxx-qt-gen/src/parser/inherit.rs
- crates/cxx-qt-gen/src/parser/signals.rs
- crates/cxx-qt-gen/src/syntax/foreignmod.rs
We do not need to consider verbatim code paths for parsing unsafe extern "ABI" anymore, this is supportted in syn 2.
eg compare ItemForeignMod and notice Option<Unsafe>
syn 1 https://docs.rs/syn/1.0.109/syn/struct.ItemForeignMod.html
syn 2 https://docs.rs/syn/2.0.0/syn/struct.ItemForeignMod.html
> cxx-qt-gen: syn 2 supports unsafety in ItemForeignMod

- crates/cxx-qt-gen/src/generator/cpp/property/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/signal.rs
- crates/cxx-qt-gen/src/generator/naming/signals.rs
- crates/cxx-qt-gen/src/generator/rust/property/mod.rs
- crates/cxx-qt-gen/src/generator/rust/signals.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.cpp
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.h
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.cpp
- crates/cxx-qt-gen/test_outputs/properties.h
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-gen/test_outputs/signals.cpp
- crates/cxx-qt-gen/test_outputs/signals.h
- crates/cxx-qt-gen/test_outputs/signals.rs
This is now unused as the type conversion has been removed.
Requires #554 
Requires #571
> cxx-qt-gen: remove generation of wrapper for emitting signals

- CHANGELOG.md
- book/src/SUMMARY.md
- book/src/concepts/inheritance.md
- book/src/getting-started/1-qobjects-in-rust.md
- book/src/qobject/index.md
- book/src/qobject/qobject_struct.md
- book/src/qobject/signals.md
- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
- crates/cxx-qt-gen/src/parser/inherit.rs
- crates/cxx-qt-gen/src/parser/mod.rs
- crates/cxx-qt-gen/src/parser/signals.rs
- crates/cxx-qt-gen/src/syntax/attribute.rs
- crates/cxx-qt-gen/test_inputs/inheritance.rs
- crates/cxx-qt-gen/test_inputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_inputs/signals.rs
- crates/cxx-qt-macro/src/lib.rs
- crates/cxx-qt/src/lib.rs
- examples/demo_threading/rust/src/lib.rs
- examples/qml_features/rust/src/custom_base_class.rs
- examples/qml_features/rust/src/multiple_qobjects.rs
- examples/qml_features/rust/src/nested_qobjects.rs
- examples/qml_features/rust/src/serialisation.rs
- examples/qml_features/rust/src/signals.rs
> cxx-qt-gen: use extern "RustQt" block for inherit and signals

- crates/cxx-qt-build/src/lib.rs
- crates/qt-build-utils/src/lib.rs
For some targets the moc compiler requires that the -Muri option should be passed for all qobjects. If this is not done the resulting qml application would not be able to find the qobject and will fail to load.
> Pass the qobject uri's to the moc compiler with the -Muri option.

- examples/demo_threading/qml/MainWindow.qml
- examples/demo_threading/rust/src/lib.rs
- examples/qml_features/CMakeLists.txt
- examples/qml_features/qml/main.qml
- examples/qml_features/qml/pages/CustomParentClassPage.qml
- examples/qml_features/qml/qml.qrc
- examples/qml_features/rust/build.rs
- examples/qml_features/rust/src/custom_parent_class.rs
- examples/qml_features/rust/src/lib.rs
This then allows you to create a QQuickItem such as a QQuickPaintedItem.
Closes #474
> add QQuickPaintedItem example using Constructor trait

- CHANGELOG.md
- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
- crates/cxx-qt-gen/src/parser/qobject.rs
- crates/cxx-qt-gen/test_inputs/invokables.rs
- crates/cxx-qt-gen/test_inputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt/src/lib.rs
- examples/demo_threading/rust/src/lib.rs
- examples/qml_features/rust/src/custom_base_class.rs
- examples/qml_features/rust/src/custom_parent_class.rs
- examples/qml_features/rust/src/multiple_qobjects.rs
- examples/qml_features/rust/src/nested_qobjects.rs
- examples/qml_features/rust/src/signals.rs
- examples/qml_features/rust/src/threading.rs
- tests/basic_cxx_qt/rust/src/lib.rs
- tests/basic_cxx_qt/rust/src/locking.rs
> cxx-qt-gen: remove qobject:: from impl a trait for a qobject in a bridge

- crates/cxx-qt-gen/src/generator/cpp/invokable.rs
- crates/cxx-qt-gen/src/generator/rust/invokable.rs
- crates/cxx-qt-gen/test_outputs/inheritance.cpp
- crates/cxx-qt-gen/test_outputs/inheritance.h
- crates/cxx-qt-gen/test_outputs/inheritance.rs
- crates/cxx-qt-gen/test_outputs/invokables.cpp
- crates/cxx-qt-gen/test_outputs/invokables.h
- crates/cxx-qt-gen/test_outputs/invokables.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.cpp
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.h
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/signals.cpp
- crates/cxx-qt-gen/test_outputs/signals.h
- crates/cxx-qt-gen/test_outputs/signals.rs
This then avoids us needing to generate Rust methods with fully qualified types on the Rust side and removes a load of generation.
Related to #404
> cxx-qt-gen: remove wrapper method for C++ -> Rust invokables

- crates/cxx-qt-gen/src/generator/cpp/property/getter.rs
- crates/cxx-qt-gen/src/generator/cpp/property/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/property/setter.rs
- crates/cxx-qt-gen/src/generator/naming/property.rs
- crates/cxx-qt-gen/src/generator/rust/property/getter.rs
- crates/cxx-qt-gen/src/generator/rust/property/mod.rs
- crates/cxx-qt-gen/src/generator/rust/property/setter.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.cpp
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.h
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.cpp
- crates/cxx-qt-gen/test_outputs/properties.h
- crates/cxx-qt-gen/test_outputs/properties.rs
This then avoids us needing to generate Rust methods with
fully qualified types on the Rust side and removes a load of
generation.
Related to #404
Requires #589
> cxx-qt-gen: remove wrapper method for C++ -> Rust properties

- CHANGELOG.md
- crates/cxx-qt-gen/src/generator/rust/property/mod.rs
- crates/cxx-qt-gen/src/generator/rust/property/setter.rs
- crates/cxx-qt-gen/src/generator/rust/signals.rs
- crates/cxx-qt-gen/src/generator/rust/threading.rs
- crates/cxx-qt-gen/src/writer/rust/mod.rs
- crates/cxx-qt-gen/test_outputs/inheritance.rs
- crates/cxx-qt-gen/test_outputs/invokables.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-gen/test_outputs/signals.rs
- crates/cxx-qt-lib/src/core/qcoreapplication.rs
- crates/cxx-qt-lib/src/gui/qguiapplication.rs
- examples/demo_threading/rust/src/workers/sensors.rs
- tests/qt_types_standalone/rust/src/qbytearray.rs
- tests/qt_types_standalone/rust/src/qstring.rs
Now that impls are outside of the bridge the developer needs to import Pin anyway.
Closes #417
Requires #553
> cxx-qt-gen: don't import Pin in hidden module resolving IDE integration

- crates/cxx-qt-gen/src/generator/cpp/constructor.rs
- crates/cxx-qt-gen/src/generator/cpp/fragment.rs
- crates/cxx-qt-gen/src/generator/naming/qobject.rs
- crates/cxx-qt-gen/src/generator/rust/constructor.rs
- crates/cxx-qt-gen/src/parser/constructor.rs
- crates/cxx-qt-gen/test_outputs/inheritance.cpp
- crates/cxx-qt-gen/test_outputs/inheritance.rs
- crates/cxx-qt-gen/test_outputs/invokables.cpp
- crates/cxx-qt-gen/test_outputs/invokables.h
- crates/cxx-qt-gen/test_outputs/invokables.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.cpp
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.cpp
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-gen/test_outputs/signals.cpp
- crates/cxx-qt-gen/test_outputs/signals.rs
> cxx_qt::Constructor: Add tests

- crates/cxx-qt-build/src/lib.rs
- crates/cxx-qt-gen/src/generator/cpp/qobject.rs
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/src/parser/qobject.rs
- crates/qt-build-utils/src/lib.rs
- examples/cargo_without_cmake/build.rs
- examples/demo_threading/rust/build.rs
- examples/demo_threading/rust/src/lib.rs
- examples/qml_features/rust/build.rs
- examples/qml_features/rust/src/containers.rs
- examples/qml_features/rust/src/custom_base_class.rs
- examples/qml_features/rust/src/invokables.rs
- examples/qml_features/rust/src/multiple_qobjects.rs
- examples/qml_features/rust/src/nested_qobjects.rs
- examples/qml_features/rust/src/properties.rs
- examples/qml_features/rust/src/serialisation.rs
- examples/qml_features/rust/src/signals.rs
- examples/qml_features/rust/src/singleton.rs
- examples/qml_features/rust/src/threading.rs
- examples/qml_features/rust/src/types.rs
- examples/qml_features/rust/src/uncreatable.rs
- examples/qml_minimal/rust/build.rs
- examples/qml_minimal/rust/src/cxxqt_object.rs
This avoids the need to repeatedly specify the URI and version of the QML module in the bridges. QObjects that are registered as QML elements are now marked by
[cxx_qt::qobject(qml_element = "OptionalName")]
This is a precursor to generating qmldir files which are required for qmlcachegen and qmltc
(https://github.com/KDAB/cxx-qt/issues/242)
> move QML element registration to build.rs instead of bridge

- crates/cxx-qt-gen/src/generator/rust/constructor.rs
- crates/cxx-qt-gen/src/generator/rust/cxxqttype.rs
- crates/cxx-qt-gen/src/generator/rust/inherit.rs
- crates/cxx-qt-gen/src/generator/rust/invokable.rs
- crates/cxx-qt-gen/src/generator/rust/mod.rs
- crates/cxx-qt-gen/src/generator/rust/property/getter.rs
- crates/cxx-qt-gen/src/generator/rust/property/mod.rs
- crates/cxx-qt-gen/src/generator/rust/property/setter.rs
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/src/generator/rust/signals.rs
- crates/cxx-qt-gen/src/generator/rust/threading.rs
- crates/cxx-qt-gen/src/generator/utils/rust.rs
- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
- crates/cxx-qt-gen/src/parser/mod.rs
- crates/cxx-qt-gen/src/writer/rust/mod.rs
- crates/cxx-qt-gen/test_inputs/invokables.rs
- crates/cxx-qt-gen/test_outputs/inheritance.rs
- crates/cxx-qt-gen/test_outputs/invokables.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-gen/test_outputs/signals.rs
Requires #617 #587 #620
And needs
> cxx-qt-gen: remove hidden module

- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
- crates/cxx-qt-gen/src/parser/mod.rs
- crates/cxx-qt-gen/src/syntax/path.rs
This then allows us to easily parse extern "C++Qt" later.
Requires #618 and starts splitting up #622 into commits.
> cxx-qt-gen: parse all items and use Path::get_ident instead of helper

- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
- crates/cxx-qt-gen/src/parser/mod.rs
- crates/cxx-qt-gen/src/syntax/path.rs
This also simplifies extern "C++Qt" support later.
> cxx-qt-gen: store module ident in parser and simplify populating mapping

- examples/demo_threading/rust/src/lib.rs
- examples/qml_extension_plugin/plugin/rust/src/lib.rs
- examples/qml_features/rust/src/containers.rs
- examples/qml_features/rust/src/custom_base_class.rs
- examples/qml_features/rust/src/custom_parent_class.rs
- examples/qml_features/rust/src/invokables.rs
- examples/qml_features/rust/src/multiple_qobjects.rs
- examples/qml_features/rust/src/nested_qobjects.rs
- examples/qml_features/rust/src/properties.rs
- examples/qml_features/rust/src/serialisation.rs
- examples/qml_features/rust/src/signals.rs
- examples/qml_features/rust/src/singleton.rs
- examples/qml_features/rust/src/threading.rs
- examples/qml_features/rust/src/types.rs
- examples/qml_minimal/rust/src/lib.rs
This then shows how a doc page is generated correctly for our QObjects.
Closes #529
> examples: ensure mod and fn are pub so that doc page works

- crates/cxx-qt-gen/src/generator/cpp/constructor.rs
- crates/cxx-qt-gen/src/generator/rust/constructor.rs
- crates/cxx-qt-gen/src/parser/constructor.rs
- crates/cxx-qt-gen/src/syntax/lifetimes.rs
- crates/cxx-qt-gen/src/syntax/mod.rs
- crates/cxx-qt-gen/test_inputs/invokables.rs
- crates/cxx-qt-gen/test_outputs/invokables.cpp
- crates/cxx-qt-gen/test_outputs/invokables.h
- crates/cxx-qt-gen/test_outputs/invokables.rs
- examples/qml_features/rust/src/signals.rs
This makes it possible to have constructors take arguments by-reference, which is the default in C++.
> Allow lifetime parameters in cxx_qt::Constructors

- crates/cxx-qt-gen/src/generator/cpp/constructor.rs
- crates/cxx-qt-gen/src/generator/cpp/cxxqttype.rs
- crates/cxx-qt-gen/src/generator/cpp/locking.rs
- crates/cxx-qt-gen/src/generator/cpp/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/qobject.rs
- crates/cxx-qt-gen/src/writer/cpp/header.rs
- crates/cxx-qt-gen/src/writer/cpp/mod.rs
- crates/cxx-qt-gen/src/writer/cpp/source.rs
- crates/cxx-qt-gen/test_outputs/inheritance.cpp
- crates/cxx-qt-gen/test_outputs/inheritance.h
- crates/cxx-qt-gen/test_outputs/invokables.cpp
- crates/cxx-qt-gen/test_outputs/invokables.h
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.cpp
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.h
- crates/cxx-qt-gen/test_outputs/properties.cpp
- crates/cxx-qt-gen/test_outputs/properties.h
- crates/cxx-qt-gen/test_outputs/signals.cpp
- crates/cxx-qt-gen/test_outputs/signals.h
This potentially helpers later with generic signal connections.
> cxx-qt-gen: improve the generator / writer split

- crates/cxx-qt-gen/src/generator/cpp/constructor.rs
- crates/cxx-qt-gen/src/generator/cpp/inherit.rs
- crates/cxx-qt-gen/src/generator/cpp/method.rs
- crates/cxx-qt-gen/src/generator/cpp/property/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/qobject.rs
- crates/cxx-qt-gen/src/generator/cpp/signal.rs
- crates/cxx-qt-gen/src/generator/rust/mod.rs
- crates/cxx-qt-gen/src/generator/utils/cpp.rs
- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
- crates/cxx-qt-gen/src/parser/externcxxqt.rs
- crates/cxx-qt-gen/src/parser/mappings.rs
- crates/cxx-qt-gen/src/parser/mod.rs
> cxx-qt-gen: add parsing phase of extern "C++Qt"

- crates/cxx-qt-build/src/lib.rs
- crates/cxx-qt-lib/build.rs
> fix "file too big" error in MinGW Debug

- crates/cxx-qt-gen/include/cxxqt_locking.h
- crates/cxx-qt-gen/include/cxxqt_thread.h
- crates/cxx-qt-gen/include/cxxqt_threading.h
- crates/cxx-qt-gen/include/cxxqt_type.h
- crates/cxx-qt-gen/src/generator/cpp/constructor.rs
- crates/cxx-qt-gen/src/generator/cpp/cxxqttype.rs
- crates/cxx-qt-gen/src/generator/cpp/locking.rs
- crates/cxx-qt-gen/src/generator/cpp/qobject.rs
- crates/cxx-qt-gen/src/generator/cpp/threading.rs
- crates/cxx-qt-gen/src/lib.rs
- crates/cxx-qt-gen/src/writer/cpp/header.rs
- crates/cxx-qt-gen/src/writer/cpp/mod.rs
- crates/cxx-qt-gen/src/writer/cpp/source.rs
- crates/cxx-qt-gen/test_outputs/inheritance.cpp
- crates/cxx-qt-gen/test_outputs/inheritance.h
- crates/cxx-qt-gen/test_outputs/invokables.cpp
- crates/cxx-qt-gen/test_outputs/invokables.h
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.cpp
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.h
- crates/cxx-qt-gen/test_outputs/properties.cpp
- crates/cxx-qt-gen/test_outputs/properties.h
- crates/cxx-qt-gen/test_outputs/signals.cpp
- crates/cxx-qt-gen/test_outputs/signals.h
These mixins in the C++ side then match the traits we have on the Rust side.
This then means as a next phase we can have `MaybeLockGuard<T>` which can lock a given type if it derives from `CxxQtLocking` or do nothing if it doesn't. Which then means we can always put that in the code generation simplifying that further. Which then means for connection generation for signals of external types (like `QPushButton`) we don't need to have different generation for if it's a `CxxQtLocking` object or not :tada:  (expect this in further pull requests).
> cxx-qt-gen: use mixins for CxxQtType, CxxQtLocking, CxxQtThreading

- CHANGELOG.md
- crates/cxx-qt-lib/src/core/qcoreapplication.rs
- crates/cxx-qt-lib/src/gui/qguiapplication.rs
This should be set_organization_name rather than
q{core,gui}application_set_organization_name.
Closes #652
> cxx-qt-lib: fix Q{Core,Gui}Application setOrganizationName

- crates/cxx-qt-gen/include/cxxqt_locking.h
- crates/cxx-qt-gen/include/cxxqt_maybelockguard.h
- crates/cxx-qt-gen/src/generator/cpp/method.rs
- crates/cxx-qt-gen/src/generator/cpp/property/getter.rs
- crates/cxx-qt-gen/src/generator/cpp/property/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/property/setter.rs
- crates/cxx-qt-gen/src/generator/cpp/qobject.rs
- crates/cxx-qt-gen/src/generator/cpp/signal.rs
- crates/cxx-qt-gen/src/lib.rs
- crates/cxx-qt-gen/test_outputs/inheritance.cpp
- crates/cxx-qt-gen/test_outputs/inheritance.h
- crates/cxx-qt-gen/test_outputs/invokables.cpp
- crates/cxx-qt-gen/test_outputs/invokables.h
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.cpp
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.h
- crates/cxx-qt-gen/test_outputs/properties.cpp
- crates/cxx-qt-gen/test_outputs/properties.h
- crates/cxx-qt-gen/test_outputs/signals.cpp
- crates/cxx-qt-gen/test_outputs/signals.h
This means that all places where we need to lock can use this
and not have to worry if the type actually implements locking
or not. As MaybeLockGuard detects if the type has the
CxxQtLocking mixin.
This then simplifies connections later with extern C++ types
like QPushButton.
Requires #648
> cxx-qt-gen: add MaybeLockGuard which can optionally lock

- CHANGELOG.md
- book/src/SUMMARY.md
- book/src/concepts/constructor.md
- book/src/concepts/index.md
- book/src/concepts/inheritance.md
- crates/cxx-qt/src/lib.rs
- examples/qml_features/rust/src/custom_parent_class.rs
- examples/qml_features/rust/src/nested_qobjects.rs
- examples/qml_features/rust/src/properties.rs
- examples/qml_features/rust/src/signals.rs
> Constructor documentation

- crates/cxx-qt-gen/src/generator/cpp/method.rs
- crates/cxx-qt-gen/src/generator/cpp/property/getter.rs
- crates/cxx-qt-gen/src/generator/cpp/property/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/property/setter.rs
- crates/cxx-qt-gen/src/generator/cpp/qobject.rs
- crates/cxx-qt-gen/src/generator/cpp/signal.rs
Later we have locks that require different parameters than *this so instead just generate them when needed which is easily done from the already known qobject_ident.
> cxx-qt-gen: do not pass lock_guard around instead just generate it

- crates/cxx-qt-gen/src/generator/cpp/property/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/signal.rs
- crates/cxx-qt-gen/src/writer/cpp/header.rs
- crates/cxx-qt-gen/src/writer/cpp/mod.rs
- crates/cxx-qt-gen/src/writer/cpp/source.rs
This helps us with signal generation for extern "C++Qt" blocks later.
> cxx-qt-gen: more generic helpers for namespaces and signals

- crates/cxx-qt-gen/src/generator/cpp/constructor.rs
- crates/cxx-qt-gen/src/generator/cpp/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/qobject.rs
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/src/writer/cpp/header.rs
- crates/cxx-qt-gen/src/writer/cpp/mod.rs
- crates/cxx-qt-gen/src/writer/cpp/source.rs
- crates/cxx-qt-gen/test_inputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/invokables.cpp
- crates/cxx-qt-gen/test_outputs/invokables.h
- crates/cxx-qt-gen/test_outputs/invokables.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.cpp
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.h
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.cpp
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-gen/test_outputs/qenum.cpp
- crates/cxx-qt-gen/test_outputs/qenum.rs
- crates/cxx-qt-gen/test_outputs/signals.cpp
- crates/cxx-qt-gen/test_outputs/signals.rs
Previously, specifying a `#[namespace="..."]` directly on a QObject didn't correctly overwrite the bridge namespace.
> Fix namespace generation of QObjects

- crates/cxx-qt-gen/src/generator/cpp/signal.rs
- crates/cxx-qt-gen/src/generator/naming/signals.rs
- crates/cxx-qt-gen/src/generator/rust/signals.rs
- crates/cxx-qt-gen/src/parser/signals.rs
> cxx-qt-gen: support private signals on the extern "C++Qt"

- CHANGELOG.md
- CMakeLists.txt
- examples/demo_threading/CMakeLists.txt
- examples/qml_features/CMakeLists.txt
- examples/qml_minimal/CMakeLists.txt
- tests/basic_cxx_only/CMakeLists.txt
- tests/basic_cxx_qt/CMakeLists.txt
- tests/qt_types_standalone/CMakeLists.txt
Related to #682
Related to #676
> cmake: set MSVC_RUNTIME_LIBRARY to MultiThreadedDLL

- crates/cxx-qt-lib/src/core/qdatetime.rs
- crates/cxx-qt-lib/src/core/qstring.rs
incorrect implementation of `partial_cmp` on an `Ord` type
> cxx-qt-lib: fix new clippy warning for PartialOrd and Ord impls

- crates/cxx-qt-lib/src/core/qdatetime.rs
- crates/cxx-qt-lib/src/core/qstring.rs
This meant that QString and QDateTime had reversed Ord results.
> cxx-qt-lib: fix incorrect cmp order

- CMakeLists.txt
Defining the macro before including any Qt header will disable the overload of QObject::connect that does not take a receiver/context argument.
> Use new QT_NO_CONTEXTLESS_CONNECT variable in qt6

- crates/cxx-qt-gen/include/cxxqt_locking.h
Removed the following warning:
```
warning: /Users/michael/projects/qml_minimal_copy/build/cxxqt/qml-minimal/cxx-qt-common/cxxqt_maybelockguard.h:21:1: warning: 'MaybeLockGuard' defined as a struct template here but previously declared as a class template; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
warning: struct MaybeLockGuard
warning: ^
warning: /Users/michael/projects/qml_minimal_copy/build/cxxqt/qml-minimal/cxx-qt-common/cxxqt_locking.h:35:10: note: did you mean struct here?
warning:   friend class MaybeLockGuard;
warning:          ^~~~~
warning:          struct
```
> Remove "defined as struct" warning

- examples/cargo_without_cmake/CMakeLists.txt
- examples/demo_threading/CMakeLists.txt
- examples/qml_features/CMakeLists.txt
- examples/qml_minimal/CMakeLists.txt
- tests/basic_cxx_qt/CMakeLists.txt
- tests/qt_types_standalone/CMakeLists.txt
Otherwise when build in an environment with only Qt5 you have to still specify USE_QT5=true.
This reverts commit 834cd850a49e451445fd866eb18772485b63e1da.
> revert "Make modules required"

- crates/cxx-qt-lib-headers/include/core/qmodelindex.h
- crates/cxx-qt-lib/src/core/qmodelindex.cpp
- crates/cxx-qt-lib/src/core/qmodelindex.rs
Implementation of QModelIndex::internalId for #719 using a wrapper function.
The direct solution 
#[rust_name = "internalId"]
fn internal_id(self: &QModelIndex) -> usize;
didn't compile. There was a type mismatch between ::std::size_t (unsigned long) and quintptr (unsigned long long) on my system (Apple Silicon, stable-aarch64-apple-darwin).
This PR enables trees via QAbstractItemModel.
> Wrapper for QModelIndex::internalId

- crates/cxx-qt-gen/src/generator/cpp/property/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/signal.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.cpp
- crates/cxx-qt-gen/test_outputs/properties.cpp
- crates/cxx-qt-gen/test_outputs/signals.cpp
This fixes warnings in CI from macOS using clang.
> cxx-qt-gen: add missing noexcept to SignalHandler deconstructor

- crates/cxx-qt-lib-headers/include/gui/qimage.h
- crates/cxx-qt-lib-headers/src/lib.rs
- crates/cxx-qt-lib/build.rs
- crates/cxx-qt-lib/src/gui/mod.rs
- crates/cxx-qt-lib/src/gui/qimage.cpp
- crates/cxx-qt-lib/src/gui/qimage.rs
Just enough to make the qt-tutorial for KDAB Training day work.
> Minimal implementation of QImage.

- crates/qt-build-utils/src/lib.rs
This is required to link together multiple QML modules in one project without duplicate symbol errors. This fixes the link error in #598.
> qt-build-utils: use QML module name in .qrc file name

- CHANGELOG.md
- crates/cxx-qt-lib-headers/include/common.h
- crates/cxx-qt-lib/src/core/mod.rs
- crates/cxx-qt-lib/src/core/qmodelindex.rs
- tests/qt_types_standalone/cpp/qmodelindex.h
- tests/qt_types_standalone/rust/src/qmodelindex.rs
> CXX-Qt-lib: Add QModelIndex::internalPointer

- crates/cxx-qt-lib/src/gui/mod.rs
- crates/cxx-qt-lib/src/gui/qimage.rs
* Rename the method from_height_width_and_format to match its signature. This is a breaking change, but the method has not appeared in a release so far.
* Expose QImageFormat so that the method can be called without ugly hacks.
> Fix usability of QImage construction

- .github/workflows/github-cxx-qt-tests.yml
It takes long time + it's already executes in linux/windows
> Disable cargo_clippy and cargo_doc on macos

- .github/workflows/github-cxx-qt-tests.yml
Cargo doc is somewhat redundant to run on multiple platforms.
Same with cargo clippy, though we'll loose clippy lints for code that uses #[cfg(target_os="...")].
We expect this change to speed up CI by 5-10 min. though, which is likely worth it.
> Don't run cargo clippy & cargo doc on Windows

- .github/workflows/github-cxx-qt-tests.yml
- book/.markdownlint.json
- book/.markdownlint.jsonc
only lints in book for now, the rules may have to be different for changelog & readme or they may need to be edited to conform or just have comments turning certain rules off
resolves #800
> CI: markdown-lint

- CHANGELOG.md
- crates/cxx-qt/src/threading.rs
This then means it can be used in async blocks too.
Closes #481
> cxxqtthread: add Sync marker so that it can be used by reference

- crates/qt-build-utils/src/lib.rs
Otherwise we have a build failure as qmlcache_loader.cpp file does not exist.
> qt-build-utils: only run qmlcachegen when there are QML files

- .github/workflows/github-cxx-qt-tests.yml
https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/
> github: use 4 cores and 3 cores when available in CI

- .github/workflows/book.yml
- .github/workflows/github-cxx-qt-tests.yml
- .github/workflows/manual-book.yml
Before we had the problem that we tried to always restore the same cache but only save it when a commit reached `main`, this had the problem that if nothing reached `main` the cache would expire after 1 week.
Instead always save the cache, this will cause the cache to have some items from branches, but is probably still more beneficial and allows us to avoid evictions.
> github: always use same cache rather than creating new ones

- crates/cxx-qt-gen/src/generator/cpp/externcxxqt.rs
- crates/cxx-qt-gen/src/generator/cpp/method.rs
- crates/cxx-qt-gen/src/generator/cpp/property/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/qenum.rs
- crates/cxx-qt-gen/src/generator/cpp/signal.rs
- crates/cxx-qt-gen/src/generator/naming/signals.rs
- crates/cxx-qt-gen/src/generator/rust/constructor.rs
- crates/cxx-qt-gen/src/generator/rust/cxxqttype.rs
- crates/cxx-qt-gen/src/generator/rust/property/getter.rs
- crates/cxx-qt-gen/src/generator/rust/property/mod.rs
- crates/cxx-qt-gen/src/generator/rust/property/setter.rs
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/src/generator/rust/signals.rs
- crates/cxx-qt-gen/src/generator/rust/threading.rs
- crates/cxx-qt-gen/src/generator/utils/cpp.rs
- crates/cxx-qt-gen/src/generator/utils/rust.rs
- crates/cxx-qt-gen/src/parser/mod.rs
- crates/cxx-qt-gen/src/parser/naming.rs
This should be a responsibility of the TypeNames struct in the future.
> Refactor syn_type_to_cpp_type

- Cargo.toml
1.0.85 includes https://github.com/rust-lang/cc-rs/pull/918 and the macOS deployment target issue has been fixed.
> update cc crate to 1.0.86

- .github/workflows/github-cxx-qt-tests.yml
Previously, it would skip updating, as the key is always the same. That meant the cache got progressively older.
> CI: Always update the compiler cache

- CHANGELOG.md
- crates/cxx-qt-gen/src/generator/cpp/constructor.rs
- crates/cxx-qt-gen/src/generator/cpp/inherit.rs
- crates/cxx-qt-gen/src/generator/cpp/qobject.rs
- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
- crates/cxx-qt-gen/src/parser/qobject.rs
- crates/cxx-qt-gen/src/writer/cpp/header.rs
- crates/cxx-qt-gen/src/writer/cpp/mod.rs
This allows for using CXX-Qt helpers with normal C++ classes, eg #[inherit] and #[cxx_override] etc.
> cxx-qt-gen: allow for optional #[qobject] macro

- .github/workflows/github-cxx-qt-tests.yml
The issue around meson not working with Python 3.12 has been resolved so we can move to the next release https://github.com/microsoft/vcpkg/issues/35332
> vcpkg: update to 2024.03.19 which supports Python 3.12

- crates/cxx-qt-lib-headers/include/common.h
This PR also includes small changes to make_unique and make_shared, so they are properly forwarding their arguments.
see #823
> add new_ptr template

- crates/cxx-qt-build/src/lib.rs
- crates/cxx-qt/build.rs
This then works in a common way with MSVC and GCC/Clang etc
> build: use .std("c++17") instead of flag_if_supported

- crates/qt-build-utils/src/lib.rs
> qt-build-utils: when using frameworks add QT_INSTALL_LIBS explicitly

- crates/cxx-qt-gen/src/generator/rust/property/mod.rs
- crates/cxx-qt-gen/src/generator/rust/signals.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-gen/test_outputs/signals.rs
- crates/cxx-qt/src/connectionguard.rs
- examples/cargo_without_cmake/src/main.rs
Before we used to return a QMetaObjectConnection which used to disconnection now we have two types, so ensure #[must_use] is in the right place.
Closes #930
> signals: use #[must_use] when returning a QMetaObjectConnectionGuard

- .github/workflows/github-cxx-qt-tests.yml
- CHANGELOG.md
- Cargo.toml
- crates/cxx-qt-build/src/lib.rs
- crates/cxx-qt-gen/src/generator/cpp/externcxxqt.rs
- crates/cxx-qt-gen/src/syntax/mod.rs
- crates/cxx-qt-lib-headers/include/core/qdatetime.h
- crates/cxx-qt-lib/build.rs
- crates/cxx-qt-lib/src/core/qdatetime.cpp
- crates/cxx-qt-lib/src/core/qdatetime.rs
- crates/qt-build-utils/src/lib.rs
- examples/cargo_without_cmake/CMakeLists.txt
- examples/demo_threading/CMakeLists.txt
- examples/qml_features/CMakeLists.txt
- examples/qml_minimal/CMakeLists.txt
So far this is
- abdd6893 (fix corrosion build failure)
- bc12e66e (fix clippy warnings)
- 295f761a (move to macOS12)
- f62c1013 (use newer vcpkg)
- a5f923f9 (fix Python version with macOS)
- a47e7f16 (match macOS version)
- 55befe12 (improve apple linking to clang_rt)
- 1342bf43 (improve apple linking to clang_rt)
- 07f880a7 (run QML cachegen when required)
- d8770614 (add missing include)
- 188e562a (Qt 6.7 fix)
- 46061ff5 (fix unused import)
- fad7084d (fix clippy warnings)
- 25bd6fce5af399b114b39d03d545073bd508ba58 (allow builds with no files)
- 25a553d8c9357ed02aaa0cded59a351105ead91e (apple framework improvements)
- 8b809e8b4102fdac0690161bf3264ff65864432e (cc bump to 1.0.89 for get_files)
Further commits
> Backports for 0.6.1

- CHANGELOG.md
- crates/cxx-qt-gen/src/generator/cpp/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/qenum.rs
- crates/cxx-qt-gen/src/generator/cpp/qobject.rs
- crates/cxx-qt-gen/src/generator/rust/qenum.rs
- crates/cxx-qt-gen/src/generator/structuring/mod.rs
- crates/cxx-qt-gen/src/parser/mod.rs
- crates/cxx-qt-gen/src/parser/qenum.rs
- crates/cxx-qt-gen/test_inputs/qenum.rs
- crates/cxx-qt-gen/test_outputs/qenum.cpp
- crates/cxx-qt-gen/test_outputs/qenum.h
- crates/cxx-qt-gen/test_outputs/qenum.rs
There is really no reason the QEnum must inherit the QObject namespace.
Even makes our code generation a lot simpler.
Closes #945
> refactor: Free namespacing on associated QEnum

- .github/workflows/github-cxx-qt-tests.yml
This may fix our CI issues on Windows, as they seem to have appeared with the 1.78 update
> fix: CI: Force use of Rust 1.77

- crates/cxx-qt-gen/src/generator/cpp/constructor.rs
- crates/cxx-qt-gen/src/generator/cpp/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/qobject.rs
- crates/cxx-qt-gen/src/naming/name.rs
- crates/cxx-qt-gen/src/naming/type_names.rs
- crates/cxx-qt-gen/src/parser/mod.rs
- crates/cxx-qt-gen/src/writer/cpp/header.rs
- crates/cxx-qt-gen/src/writer/cpp/mod.rs
- crates/cxx-qt-gen/src/writer/cpp/source.rs
> refactor: Use Name for C++ QObject generation

- examples/demo_threading/rust/Cargo.toml
We do not need the feature v4 as we only read uuids not generate.
> demo_threading: remove dependency on random

- crates/cxx-qt-gen/src/generator/cpp/cxxqttype.rs
- crates/cxx-qt-gen/src/generator/cpp/externcxxqt.rs
- crates/cxx-qt-gen/src/generator/cpp/method.rs
- crates/cxx-qt-gen/src/generator/cpp/property/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/property/signal.rs
- crates/cxx-qt-gen/src/generator/cpp/qobject.rs
- crates/cxx-qt-gen/src/generator/cpp/signal.rs
- crates/cxx-qt-gen/src/generator/cpp/threading.rs
- crates/cxx-qt-gen/src/generator/naming/qobject.rs
- crates/cxx-qt-gen/src/generator/naming/signals.rs
- crates/cxx-qt-gen/src/generator/rust/constructor.rs
- crates/cxx-qt-gen/src/generator/rust/cxxqttype.rs
- crates/cxx-qt-gen/src/generator/rust/externcxxqt.rs
- crates/cxx-qt-gen/src/generator/rust/inherit.rs
- crates/cxx-qt-gen/src/generator/rust/method.rs
- crates/cxx-qt-gen/src/generator/rust/property/getter.rs
- crates/cxx-qt-gen/src/generator/rust/property/mod.rs
- crates/cxx-qt-gen/src/generator/rust/property/setter.rs
- crates/cxx-qt-gen/src/generator/rust/property/signal.rs
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/src/generator/rust/signals.rs
- crates/cxx-qt-gen/src/generator/rust/threading.rs
- crates/cxx-qt-gen/src/naming/name.rs
- crates/cxx-qt-gen/src/naming/type_names.rs
> Refactor: Use naming::Name in QObjectNames struct

- CHANGELOG.md
- CMakeLists.txt
- crates/cxx-qt-lib-headers/Cargo.toml
- crates/cxx-qt-lib-headers/include/quickcontrols/qquickstyle.h
- crates/cxx-qt-lib-headers/src/lib.rs
- crates/cxx-qt-lib/Cargo.toml
- crates/cxx-qt-lib/build.rs
- crates/cxx-qt-lib/src/lib.rs
- crates/cxx-qt-lib/src/quickcontrols/mod.rs
- crates/cxx-qt-lib/src/quickcontrols/qquickstyle.cpp
- crates/cxx-qt-lib/src/quickcontrols/qquickstyle.rs
- tests/basic_cxx_only/CMakeLists.txt
- tests/basic_cxx_qt/CMakeLists.txt
- tests/qt_types_standalone/CMakeLists.txt
This is used to control which Quick Controls style is used in the application. This is part of the Quick Controls API and requires the QuickControls2 Qt module, so it's separated into another folder in cxx-qt-lib.
Example:
```rust
QQuickStyle::setStyle(&QString::from("Basic"));
QQuickStyle::setFallbackStyle(&QString::from("Material"));
println!("Style name: {}", QQuickStyle::name());
```
This is a pretty common pattern in KDE applications, and a pretty low-hanging fruit.
> Add QtQuickControls module to cxx-qt-lib, expose QQuickStyle

- examples/qml_minimal/qml/main.qml
Added color properties based off of the palette to the minimal qml example, as the labels were invisible (white text on white bg)
> Fix palette issue in qml_minimal example

- examples/qml_features/CMakeLists.txt
- examples/qml_minimal/CMakeLists.txt
- tests/CMakeLists.txt
This avoids windows popping up when running the tests for qml_features and qml_minimal.
> fix: Use QT_QPA_PLATFORM=offscreen in tests

- crates/cxx-qt-macro/Cargo.toml
- crates/cxx-qt/Cargo.toml
This was causing a duplicate build of cxx-qt-lib, which caused the file locking issues we observed in CI.
This should also speed up the CI run for cargo_test, as it's not building -lib twice now.
However, this doesn't yet solve the inherent issue that Cargo may run build scripts of different configurations in parallel. So this remains a TODO!
> fix: Remove dev-dependencies on cxx-qt-lib

- crates/cxx-qt-gen/src/generator/cpp/method.rs
- crates/cxx-qt-gen/src/generator/cpp/property/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/qobject.rs
- crates/cxx-qt-gen/src/generator/cpp/signal.rs
- crates/cxx-qt-gen/src/generator/rust/method.rs
- crates/cxx-qt-gen/src/generator/rust/mod.rs
- crates/cxx-qt-gen/src/generator/rust/property/mod.rs
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/src/generator/rust/signals.rs
The generators and tests should now be using StructuredQObject and its fields, methods and signals, in place of ParsedQobject and it's fields of the same name, this includes:
- Rewriting some of the generate functions in order to accept &Vec<&T> where they used to accept &Vec<T> and all the use of these to follow that
- Rewriting the rust generators to accept StructuredQObject instead of ParsedQObject
- Rewriting the generator functions to push methods from StructuredQObject
> Refactor to use Structuring for methods and signals

- crates/cxx-qt-gen/src/generator/structuring/mod.rs
- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
- crates/cxx-qt-gen/src/parser/mod.rs
- crates/cxx-qt-gen/src/parser/qobject.rs
Remove the now unused method and signals fields from ParsedQObject since they are now created inside StructuredQObject instead, and update a few tests
> Refactor to remove method fields in ParsedQObject

- crates/cxx-qt-gen/src/generator/cpp/property/signal.rs
- crates/cxx-qt-gen/src/generator/cpp/signal.rs
- crates/cxx-qt-gen/src/generator/naming/signals.rs
- crates/cxx-qt-gen/src/generator/rust/property/mod.rs
- crates/cxx-qt-gen/src/generator/rust/property/signal.rs
- crates/cxx-qt-gen/src/generator/rust/signals.rs
- crates/cxx-qt-gen/src/parser/signals.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.rs
Removes some old code in ParsedSignal creation for adding cxx_name, as this is now handled by Name. Refactored from just using the ForeignItemFn that was passed, to custom building the token stream like is done for ParsedMethod, including docs passthrough and cxx_names on all signals
- Update tests with new order for doc and cxx_name
- Update test_outputs for new attribute parsing
- Add doc field to ParsedSignal for passthrough
- Update tests to ignore unknown attributes like #[my_attribute]
- Update from_property_method of ParsedSignal to accept docs
> Refactor ParsedSignal to remove old code

- crates/cxx-qt-gen/src/generator/cpp/method.rs
- crates/cxx-qt-gen/src/generator/cpp/mod.rs
- crates/cxx-qt-gen/src/generator/mod.rs
- crates/cxx-qt-gen/src/generator/rust/method.rs
- crates/cxx-qt-gen/src/generator/rust/mod.rs
- crates/cxx-qt-gen/src/generator/rust/signals.rs
get_params_tokens is now in generator/rust/mod.rs, and get_cpp_params is now in generator/cpp/mod.rs.
> Move generator helpers to their language specific directories

- examples/qml_features/rust/src/custom_parent_class.rs
Clippy started complaining about an unused struct which it previously didn't mind, so just removed those lines
> Hotfix update clippy example

- crates/cxx-qt-gen/src/generator/structuring/mod.rs
- crates/cxx-qt-gen/src/generator/structuring/qobject.rs
- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
Start moving ParsedInheritedMethod into structuring phase by adding fields to StructuredQObject and ParsedCxxQtData, and associate inherited methods with their StructuredQObject in structuring phase.
> Add support for inherited method to structuring phase

- crates/cxx-qt-gen/src/generator/cpp/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/property/mod.rs
- crates/cxx-qt-gen/src/generator/cpp/qobject.rs
- crates/cxx-qt-gen/src/generator/naming/property.rs
- crates/cxx-qt-gen/src/generator/rust/mod.rs
- crates/cxx-qt-gen/src/generator/rust/property/mod.rs
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/src/generator/structuring/qobject.rs
- crates/cxx-qt-gen/src/parser/qobject.rs
- crates/cxx-qt-gen/test_inputs/properties.rs
- crates/cxx-qt-gen/test_outputs/properties.cpp
- crates/cxx-qt-gen/test_outputs/properties.h
- crates/cxx-qt-gen/test_outputs/properties.rs
StructuredQObject is passed through various functions so that in NameState, a method lookup can be used for the user defined functions, and this also requires modifying some test data to create Structures
> Introduce method lookup into NameState so that cxx_names can be used

- crates/cxx-qt-gen/src/generator/cpp/inherit.rs
- crates/cxx-qt-gen/src/generator/cpp/qobject.rs
- crates/cxx-qt-gen/src/generator/rust/inherit.rs
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
Use structured_qobject.inherited_methods in place of qobject.inherited_methods
> Refactor use inherited methods from structuring

- .github/workflows/github-cxx-qt-tests.yml
- codecov.yml
Setup codecov.io as a coverage tool, generating reports with grcov and publishing them in a CI action.
This should also allow codecov.io's bot to leave comments in PRs about coverage info, and disallow them if coverage drops too much
> Setup Code coverage

- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
- crates/cxx-qt-gen/src/parser/qobject.rs
ParsedQObject doesn't have an inherited_methods field anymore, it's been fully moved into StructuredQObject
> Refactor remove dead inherited method

- .github/workflows/github-cxx-qt-tests.yml
- crates/cxx-qt-gen/src/lib.rs
- scripts/grcov_cxx_qt.sh
Also adds markers in src/lib.rs to exclude lines used in the update_expected script
- CODECOV_EXCLUDE_START in a comment before the block to exclude
- CODECOV_EXCLUDE_STOP in a comment after the block
> Add exclude flags to grcov in CI

- crates/cxx-qt-gen/src/syntax/foreignmod.rs
- crates/cxx-qt-gen/src/syntax/lifetimes.rs
- crates/cxx-qt-gen/src/syntax/qtfile.rs
- crates/cxx-qt-gen/src/syntax/qtitem.rs
- crates/cxx-qt-gen/test_inputs/shebang.rs
- crates/cxx-qt-gen/test_inputs/shebang.rs.license
Includes adding a new test input file for reading shebang, and also for parsing of cxx and regular rust items by CxxQtFile
> Improve code coverage in syntax directory

- crates/cxx-qt-gen/src/syntax/foreignmod.rs
Use of `syn::parse2( quote! { ... } ).unwrap()` should be avoided as per #638, instead preferring to use `parse_quote! { ... }`
> Replace use of syn::parse2(quote! {...}).unwrap()

- crates/cxx-qt-gen/src/generator/cpp/method.rs
- crates/cxx-qt-gen/src/generator/cpp/qobject.rs
- crates/cxx-qt-gen/src/generator/cpp/signal.rs
- crates/cxx-qt-gen/src/generator/mod.rs
- crates/cxx-qt-gen/src/generator/naming/method.rs
- crates/cxx-qt-gen/src/generator/naming/property.rs
- crates/cxx-qt-gen/src/generator/naming/signals.rs
- crates/cxx-qt-gen/src/generator/rust/fragment.rs
- crates/cxx-qt-gen/src/generator/rust/method.rs
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/src/generator/rust/signals.rs
- crates/cxx-qt-gen/src/parser/method.rs
- crates/cxx-qt-gen/src/parser/signals.rs
- crates/cxx-qt-gen/src/writer/cpp/header.rs
- crates/cxx-qt-gen/src/writer/cpp/mod.rs
- crates/cxx-qt-gen/src/writer/cpp/source.rs
Remove some duplication in asserts, helper functions and ParsedMethod construction. This led to introducing builder like functions for mocking methods
> Remove some duplication and improve helpers for mocking ParsedMethod

- crates/cxx-qt-gen/src/generator/naming/qobject.rs
- crates/cxx-qt-gen/src/generator/rust/method.rs
- crates/cxx-qt-gen/src/generator/rust/property/getter.rs
- crates/cxx-qt-gen/src/generator/rust/property/setter.rs
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/test_outputs/invokables.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-gen/test_outputs/qenum.rs
- crates/cxx-qt-gen/test_outputs/signals.rs
- examples/qml_minimal/rust/src/cxxqt_object.rs
Putting Namespace attrs on a type in RustQt or the block itself doesn't compile, with a big string of cpp errors.
I've tried putting namespace back into the rust generate fn, along with a host of other options, such as putting the namespace on the method block as well.
However, putting namespace on the bridge works fine, and everything works properly.
> Fix namespace bug

- crates/qt-build-utils/src/lib.rs
This resolves the following warning
```rust
warning: the borrowed expression implements the required traits
--> crates/qt-build-utils/src/lib.rs:626:21
|                                         
626 |             cmd.arg(&format!("-Muri={uri}"));
|                     ^^^^^^^^^^^^^^^^^^^^^^^ help: change this to: `format!("-Muri={uri}")`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrows_for_generic_args
= note: `#[warn(clippy::needless_borrows_for_generic_args)]` on by default
```
> clippy: fix new warnings for 1.81

- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/test_outputs/inheritance.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
For some reason when using CXX-Qt as a dependency outside of this repository, the warning about the unused struct wasn't being silenced. This PR should fix that issue
> Fix: Silence warning about unused base class

- crates/qt-build-utils/src/lib.rs
- examples/qml_features/rust/build.rs
- examples/qml_features/rust/src/empty_bridge.rs
> fix build failure with empty qml bridges (closes #1033)

- crates/cxx-qt-gen/src/generator/structuring/mod.rs
- crates/cxx-qt-gen/src/lib.rs
- crates/cxx-qt-gen/src/naming/cpp.rs
- crates/cxx-qt-gen/src/naming/type_names.rs
- crates/cxx-qt-gen/src/parser/constructor.rs
- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
- crates/cxx-qt-gen/src/parser/inherit.rs
- crates/cxx-qt-gen/src/parser/mod.rs
- crates/cxx-qt-gen/src/parser/parameter.rs
- crates/cxx-qt-gen/src/parser/property.rs
- crates/cxx-qt-gen/src/parser/qenum.rs
- crates/cxx-qt-gen/src/parser/qnamespace.rs
- crates/cxx-qt-gen/src/parser/qobject.rs
- crates/cxx-qt-gen/src/parser/signals.rs
- crates/cxx-qt-gen/src/parser/trait_impl.rs
- crates/cxx-qt-gen/src/syntax/foreignmod.rs
- crates/cxx-qt-gen/src/syntax/types.rs
- crates/cxx-qt-gen/src/writer/rust/mod.rs
assert_parse_errors is now more generic thanks to some help from Leon, and I've used this in as many places as possible.
> Refactor assert_parse_errors macro to be more generic

- crates/cxx-qt-gen/Cargo.toml
- crates/cxx-qt-lib-extras/Cargo.toml
- crates/cxx-qt-lib/Cargo.toml
- examples/demo_threading/rust/Cargo.toml
- examples/qml_features/rust/Cargo.toml
- examples/qml_minimal/rust/Cargo.toml
cxx-qt-lib-extras now uses full_qt feature, and examples now use that over full, since full has new added deps.
> Add full_qt feature and replace full with it, full now includes other deps

- crates/cxx-qt-gen/src/generator/rust/inherit.rs
- crates/cxx-qt-gen/test_inputs/inheritance.rs
- crates/cxx-qt-gen/test_outputs/inheritance.h
- crates/cxx-qt-gen/test_outputs/inheritance.rs
This used ident directly, instead of rust_unqualified()
Also, add a corresponding regression test
> Hotfix: rust_name on #[inherit]

- README.md
We should explicitly state which versions of Qt we support, and which we don't.
> Update README.md with Qt support

- .github/workflows/github-cxx-qt-tests.yml
- crates/cxx-qt-lib-extras/include/core/qcommandlineoption.h
- crates/cxx-qt-lib-extras/include/core/qcommandlineparser.h
- crates/cxx-qt-lib/include/core/qbytearray.h
- crates/cxx-qt-lib/include/core/qdatetime.h
- crates/cxx-qt-lib/include/core/qhash.h
- crates/cxx-qt-lib/include/core/qlist.h
- crates/cxx-qt-lib/include/core/qlist_qvector.h
- crates/cxx-qt-lib/include/core/qmap.h
- crates/cxx-qt-lib/include/core/qpersistentmodelindex.h
- crates/cxx-qt-lib/include/core/qset.h
- crates/cxx-qt-lib/include/core/qstring.h
- crates/cxx-qt-lib/include/core/qstringlist.h
- crates/cxx-qt-lib/include/core/qurl.h
- crates/cxx-qt-lib/include/core/qvariant.h
- crates/cxx-qt-lib/include/core/qvector.h
- crates/cxx-qt-lib/include/gui/qcolor.h
- crates/cxx-qt-lib/include/gui/qfont.h
- crates/cxx-qt-lib/include/gui/qimage.h
- crates/cxx-qt-lib/include/gui/qpainterpath.h
- crates/cxx-qt-lib/include/gui/qpen.h
- crates/cxx-qt-lib/include/gui/qpolygon.h
- crates/cxx-qt-lib/include/gui/qpolygonf.h
- crates/cxx-qt-lib/include/gui/qregion.h
- crates/cxx-qt/include/connection.h
- crates/cxx-qt/include/signalhandler.h
- crates/cxx-qt/include/thread.h
- scripts/clang_format_check.sh
- scripts/clang_format_inplace.sh
A better way would be to have a consistent clang-format version everywhere
> ci: disable failing tests due to differing clang-format on macOS

- crates/cxx-qt-lib/include/gui/qguiapplication.h
- crates/cxx-qt-lib/src/gui/qguiapplication.cpp
- crates/cxx-qt-lib/src/gui/qguiapplication.rs
Added methods : 
```rs
fn set_desktop_file_name(name: &QString);
fn desktop_file_name() -> QString;
```
This is required to set the application desktop name association on Linux. This allows desktop entries and taskbar icons.
Example: 
Example usage: https://github.com/mystchonky/kontrast-rs/blob/54ace175a97f044c714599bcbf645e95a766c8a0/src/main.rs#L14
> Add `desktopFileName` static methods to QGuiApplication

- CHANGELOG.md
- crates/cxx-qt-lib/Cargo.toml
- crates/cxx-qt-lib/build.rs
- crates/cxx-qt-lib/include/core/qanystringview.h
- crates/cxx-qt-lib/src/core/mod.rs
- crates/cxx-qt-lib/src/core/qanystringview.cpp
- crates/cxx-qt-lib/src/core/qanystringview.rs
- tests/qt_types_standalone/CMakeLists.txt
- tests/qt_types_standalone/cpp/main.cpp
- tests/qt_types_standalone/cpp/qanystringview.h
- tests/qt_types_standalone/rust/Cargo.toml
- tests/qt_types_standalone/rust/build.rs
- tests/qt_types_standalone/rust/src/lib.rs
- tests/qt_types_standalone/rust/src/qanystringview.rs
This is a read-only string type that's used in several new Qt6 APIs such as QQmlApplicationEngine::loadFromModule.
Fixes #629
> Implement QAnyStringView

- crates/cxx-qt-gen/src/generator/rust/threading.rs
- crates/cxx-qt-gen/test_outputs/invokables.rs
- crates/cxx-qt/include/thread.h
- crates/cxx-qt/src/lib.rs
- crates/cxx-qt/src/threading.rs
When combining async Rust channels and QT objects, it's really easy to end up in a situation where a message is received on the channel after the `QObject` has already been destroyed, causing `CxxQtThread::queue` to throw an exception. This PR introduces an `is_alive()` function to check the handle if it's been invalidated.
- Implement is_alive method in C++ CxxQtThread class
- Add is_alive to Rust Threading trait
- Generate FFI bindings for is_alive in cxx-qt-gen
- Expose is_alive as a public method on CxxQtThread in Rust
- Update documentation for Threading trait and CxxQtThread
> Add is_alive method to CxxQtThread

- .github/workflows/github-cxx-qt-tests.yml
This prevents dependabot/... branches from running their tests twice.
First as a push to the dependabot/... branch and then as the PR into
main.
> Disable workflow runs for pushes outside main

- crates/cxx-qt-lib-extras/Cargo.toml
- crates/cxx-qt-lib/Cargo.toml
- examples/cargo_without_cmake/build.rs
- examples/demo_threading/rust/Cargo.toml
- examples/qml_features/rust/Cargo.toml
- examples/qml_minimal/rust/Cargo.toml
This is in line with our other feature names, like qt_gui, etc.
> Rename full_qt feature to qt_full.

- crates/qt-build-utils/src/lib.rs
Before a string such as "-I /path to Qt/ -I /another/path/" would be created and then split by space. This works when there are no spaces in the string but in the example here it becomes `["-I", "/path", "to", "Qt/", "-I", "/another/path/"]`.
Instead we actually want ["-I", "/path to Qt/", "-I", "/another/path/"] or we can combine the -I and have ["-I/path to Qt/", "-I/another/path/"].
So instead build a vector of include args to give to Command args instead of splitting the string. Which then resolves having a space in your Qt or library path.
Closes #756
> qt-build-utils: do not split include paths by space

- crates/cxx-qt-build/Cargo.toml
- crates/cxx-qt-build/src/lib.rs
- crates/cxx-qt-lib/build.rs
- crates/cxx-qt/Cargo.toml
- crates/cxx-qt/build.rs
- scripts/release_crates.sh
This removes a build depends of cxx-qt-build on cxx-qt
> cxx-qt: use cxx-qt-build and reexport from cxx-qt-lib

- CHANGELOG.md
Note this could come back in an explicit form such as `#[cxx_qt::bridge(auto_camel)]`
> CHANGELOG: update to reflect implicit auto camel conversion removal

- CHANGELOG.md
- book/src/bridge/attributes.md
- book/src/bridge/extern_cppqt.md
- book/src/bridge/extern_rustqt.md
- crates/cxx-qt-gen/Cargo.toml
- crates/cxx-qt-gen/src/generator/cpp/inherit.rs
- crates/cxx-qt-gen/src/generator/cpp/property/signal.rs
- crates/cxx-qt-gen/src/generator/rust/inherit.rs
- crates/cxx-qt-gen/src/generator/rust/property/signal.rs
- crates/cxx-qt-gen/src/naming/cpp.rs
- crates/cxx-qt-gen/src/naming/name.rs
- crates/cxx-qt-gen/src/naming/type_names.rs
- crates/cxx-qt-gen/src/parser/cxxqtdata.rs
- crates/cxx-qt-gen/src/parser/externcxxqt.rs
- crates/cxx-qt-gen/src/parser/externqobject.rs
- crates/cxx-qt-gen/src/parser/inherit.rs
- crates/cxx-qt-gen/src/parser/method.rs
- crates/cxx-qt-gen/src/parser/mod.rs
- crates/cxx-qt-gen/src/parser/qenum.rs
- crates/cxx-qt-gen/src/parser/qobject.rs
- crates/cxx-qt-gen/src/parser/signals.rs
- crates/cxx-qt-gen/src/syntax/types.rs
- crates/cxx-qt-gen/test_inputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.h
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- examples/qml_features/qml/pages/NamingPage.qml
- examples/qml_features/rust/src/naming.rs
- examples/qml_features/tests/tst_naming.qml
Add an attribute for extern blocks which specifies all the items inside can have their names automatically converted to the correct case.
> Feature explicit case conversion

- .github/workflows/github-cxx-qt-tests.yml
Fix for #1079 
- MacOs 14 is now being used (most recent stable version)
- Ubuntu-24.04 is now being used (most recent stable version)
- Actions previously using ubuntu-latest have been pinned to 24.04
> Update CI runner OS versions

- Cargo.toml
Otherwise you get
```
Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `cxx-qt` does not specify a version
Note: The published dependency will use the version from crates.io,
the `path` specification will be removed from the dependency declaration.
```
> cargo: ensure version is set for all crates

- crates/cxx-qt-gen/src/generator/rust/constructor.rs
- crates/cxx-qt-gen/test_outputs/inheritance.rs
- crates/cxx-qt-gen/test_outputs/invokables.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-gen/test_outputs/qenum.rs
- crates/cxx-qt-gen/test_outputs/signals.rs
The following code
```rust
#[cxx_qt::bridge]
pub mod my_object {
unsafe extern "RustQt" {
#[qobject]
#[qml_element]
type Hello = super::HelloRust;
}
unsafe extern "RustQt" {
#[qinvokable]
pub fn say_hello(self: &Hello);
}
}
#[derive(Default)]
pub struct HelloRust {}
impl my_object::Hello {
pub fn say_hello(&self) {
println!("Hello world!");
}
}
```
Triggers 
```
❮ cargo clippy -- -W clippy::pedantic
Compiling qt-test v0.0.0-development (/Users/kristof/sources/kristof-mattei/qt-test)
warning: boxed return of the sized type `cxxqt_object::HelloRust`
--> src/cxxqt_object.rs:1:1
|
1 | #[cxx_qt::bridge]
| ^^^^^^^^^^^^^^^^^
|
= help: changing this also requires a change to the return expressions in this function
= help: for further information visit …
```
> Prevent clippy from tripping lint

- crates/cxx-qt-lib/include/core/qstringlist.h
- crates/cxx-qt-lib/src/core/qstringlist.cpp
- crates/cxx-qt-lib/src/core/qstringlist.rs
Per @LeonMatthesKDAB's [comment](https://github.com/KDAB/cxx-qt/pull/761#discussion_r1447611935), implements `Deref` and `DerefMut` for `QStringList` so it isn't necessary to reimplement the `QList` API.
> implement Deref and DerefMut for QStringList to QList<QString>

- CHANGELOG.md
- crates/cxx-qt-lib/include/core/qdatetime.h
- crates/cxx-qt-lib/src/core/qdatetime.cpp
- crates/cxx-qt-lib/src/core/qdatetime.rs
This gives cxx-qt users a way to parse QDateTime from a QString. This is using one of the QDateTime::fromString overloads.
> cxx-qt-lib: Add binding for QDateTime::fromString

- README.md
- crates/cxx-qt-build/src/dir.rs
- crates/cxx-qt-build/src/lib.rs
Addresses #1120. cxx-qt-build's current symlinking works on Unix, fails on Windows unless Developer Mode is enabled, and panics on anything else. This PR modifies the non-Unix behavior to use deep file copying rather than symlinking.
I have tested this on Windows 11 and MacOS Sequoia 15.1.1.
**Note:** I'm not sure if this PR means these lines should be removed:
https://github.com/KDAB/cxx-qt/blob/f5afefecf837e199848b99d3317a623a64767c5a/README.md?plain=1#L87-L93
> On non-Unix platforms, use deep copying rather than symlinking

- crates/cxx-qt-lib/src/core/qdate.rs
- crates/cxx-qt-lib/src/core/quuid.rs
These were using `//` instead of `///`, noticed it while adding other documentation :-)
> cxx-qt-lib: Fix some doc comment syntax errors

- crates/qt-build-utils/src/parse_cflags.rs
The current logic in qt-build-utils determines whether a file is an object file by testing whether it ends with ".o", but object files on Windows end in ".obj", resulting in numerous compiler warnings of "File path {} found in .prl file for {name}, but could not extract library base name to pass to linker command line". This PR fixes the issue.
> Fix link_qt_object_files not working on Windows

- CHANGELOG.md
- Cargo.toml
- examples/todo_app/Cargo.toml
- examples/todo_app/build.rs
- examples/todo_app/qml/main.qml
- examples/todo_app/src/main.rs
- examples/todo_app/src/todo_list.rs
This is the example code developed during the tutorial videos.
> New example: ToDo app

- crates/cxx-qt-lib/src/core/init.cpp
This is an addon to #1149 that adds `qRegisterMetaType` calls for `QList_QUuid`, `QSet_QUuid`, and `QVector_QUuid`. This should have been part of the original PR, but I didn't know about the `qRegisterMetaType` system in `cxx-qt-lib/src/core/init.cpp` at the time.
> Register QUuid container types with QML

- examples/qml_features/qml/pages/SignalsPage.qml
Apparently we missed a rename here when removing the auto conversion.
> Fix: Rename logging_enabled property

- CHANGELOG.md
- crates/cxx-qt-lib/Cargo.toml
- crates/cxx-qt-lib/src/gui/qimage.cpp
- crates/cxx-qt-lib/src/gui/qimage.rs
Because the image crate changes versions somewhat frequently, the
features in CXX-Qt are added with explicit image crate versions.
> QImage: Add conversion from image::RgbaImage

- crates/cxx-qt-gen/src/generator/rust/inherit.rs
- crates/cxx-qt-gen/src/generator/rust/property/mod.rs
- crates/cxx-qt-gen/src/generator/rust/signals.rs
- crates/cxx-qt-gen/src/naming/type_names.rs
- crates/cxx-qt-gen/test_outputs/cfgs.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-gen/test_outputs/signals.rs
- examples/qml_features/rust/src/custom_base_class.rs
Fix for https://github.com/KDAB/cxx-qt/issues/1171
- Stops adding signals to typenames
- Improves errors
> Add span to callables generation to improve error messages

- .github/workflows/github-cxx-qt-tests.yml
This avoids sccache from attempting to remove files that have already been removed.
> ci: use patched version of sccache to work around macOS issue

- CHANGELOG.md
- book/src/bridge/extern_rustqt.md
- crates/cxx-qt-gen/src/generator/cpp/method.rs
- crates/cxx-qt-gen/src/generator/rust/method.rs
- crates/cxx-qt-gen/src/parser/method.rs
- crates/cxx-qt-gen/test_inputs/invokables.rs
- crates/cxx-qt-gen/test_outputs/invokables.h
- crates/cxx-qt-gen/test_outputs/invokables.rs
- examples/qml_features/qml/pages/CustomBaseClassPage.qml
- examples/qml_features/rust/src/custom_base_class.rs
Add `Pure` virtual functions API with a new attribute
> Add pure virtuals

- .github/workflows/github-cxx-qt-tests.yml
Otherwise, backports would ruin the caches for all other branches that
target `main`.
> Fix: Only update caches when pushed to `main`

- book/src/concepts/casting.md
- crates/cxx-qt-gen/src/generator/cpp/externcxxqt.rs
- crates/cxx-qt-gen/src/generator/naming/qobject.rs
- crates/cxx-qt-gen/src/generator/rust/externcxxqt.rs
- crates/cxx-qt-gen/src/generator/rust/fragment.rs
- crates/cxx-qt-gen/src/generator/rust/mod.rs
- crates/cxx-qt-gen/src/generator/rust/qobject.rs
- crates/cxx-qt-gen/src/parser/externqobject.rs
- crates/cxx-qt-gen/src/parser/mod.rs
- crates/cxx-qt-gen/src/parser/qobject.rs
- crates/cxx-qt-gen/test_inputs/inheritance.rs
- crates/cxx-qt-gen/test_outputs/cfgs.rs
- crates/cxx-qt-gen/test_outputs/inheritance.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/signals.rs
- crates/cxx-qt-lib/src/gui/qguiapplication.rs
- crates/cxx-qt-lib/src/qml/qqmlapplicationengine.rs
- crates/cxx-qt-lib/src/quickcontrols/qquickstyle.rs
Add support for the `#[base = T]` attribute in `extern "C++Qt"` blocks, as well as casting implementations for these applicable types.
> Base on cppqt blocks

- CHANGELOG.md
- crates/cxx-qt-gen/src/naming/type_names.rs
- crates/cxx-qt-gen/src/parser/mod.rs
- crates/cxx-qt-lib/src/core/qcoreapplication.rs
- crates/cxx-qt-lib/src/gui/qguiapplication.rs
- crates/cxx-qt-lib/src/qml/qqmlapplicationengine.rs
- Add objectCreated signal to QQmlApplicationEngine
- Fixed bug where type_name doesn't recognise QObject
- Fixed qualification of QCoreApplication in bridge
> Add more signals to cxx_qt_lib

- crates/cxx-qt-lib/include/gui/qguiapplication.h
- crates/cxx-qt-lib/src/core/mod.rs
- crates/cxx-qt-lib/src/core/qflags/macros.rs
- crates/cxx-qt-lib/src/core/qflags/mod.rs
- crates/cxx-qt-lib/src/core/qflags/qflag.rs
- crates/cxx-qt-lib/src/core/qflags/repr.rs
- crates/cxx-qt-lib/src/core/qflags/util.rs
- crates/cxx-qt-lib/src/core/qt.rs
- crates/cxx-qt-lib/src/gui/qguiapplication.cpp
- crates/cxx-qt-lib/src/gui/qguiapplication.rs
- tests/qt_types_standalone/CMakeLists.txt
- tests/qt_types_standalone/cpp/main.cpp
- tests/qt_types_standalone/cpp/qflags.h
- tests/qt_types_standalone/rust/build.rs
- tests/qt_types_standalone/rust/src/lib.rs
- tests/qt_types_standalone/rust/src/qflags.rs
This PR defines a `QFlags<T: QFlag>` type to address the non-codegen parts of #1123. It mimics the API of Qt's own `QFlags`, including operators. The one exception is that because Rust doesn't have the `~` operator, the `~` operator in Qt is mapped to `!` in Rust, while the `!` operator in Qt is mapped to `QFlags::is_empty` in Rust.
The backing `QFlag` trait provides two things: a function for converting from the FFI enum type to its underlying representation (i.e. `value.repr`) and the `TypeId` of the corresponding `QFlags` type. For example:
```rs
#[cxx::bridge]
mod ffi {
#[repr(i32)]
enum MyFlag { A, B }; 
}
pub use ffi::MyFlag;
unsafe impl QFlag for MyFlag {
type TypeId = type_id!("QFlags_MyFlag");
type Repr = i32;
fn to_repr(self) -> Self::Repr {
self.repr
}
}
pub type MyFlags = …
```
> Support QFlags

- crates/cxx-qt-build/src/dir.rs
- crates/cxx-qt-build/src/lib.rs
- crates/cxx-qt-lib-extras/build.rs
- crates/cxx-qt-lib/build.rs
As described in #1237, on Windows we're sometimes hitting the 260 character limit
for filepaths.
This is mostly due to a lot of nesting by Qt Creator, Corrosion and
Cargo who all include the target triple and other configuration information in the
build path.
However, we can at least reduce the character count a little bit on our
part.
For example, for qqmlengine.cxxqt.h, the path length is now reduced by
~40 characters from:
out/cxx-qt-build/target/crates/cxx-qt-lib/include/cxx-qt-lib-internals/src/qml/qqmlengine.cxxqt.h
to now:
out/cxxqtbuild/include/private/src/qml/qqmlengine.cxxqt.h
Closes #1237
> Use shorter paths in the OUT_DIR

- book/src/bridge/extern_rustqt.md
- book/src/bridge/traits.md
- crates/cxx-qt-gen/src/parser/trait_impl.rs
- crates/cxx-qt/src/lib.rs
- examples/demo_threading/rust/src/lib.rs
- examples/qml_features/rust/src/custom_parent_class.rs
- examples/qml_features/rust/src/nested_qobjects.rs
- examples/qml_features/rust/src/properties.rs
- examples/qml_features/rust/src/signals.rs
- examples/qml_minimal/rust/src/cxxqt_object.rs
- `impl cxx_qt::Initialize for x {}` can now be written in the bridge as shorthand
- It is shorthand for `impl cxx_qt::Constructor<()> for x {}`
- Closes #1236
> Add shorthand for cxx_qt::Initialize

- .github/workflows/github-cxx-qt-tests.yml
> github: move to Qt 6.9.0 for CI tests

- .github/workflows/github-cxx-qt-tests.yml
- book/src/getting-started/5-cmake-integration.md
- examples/demo_threading/CMakeLists.txt
- examples/qml_features/CMakeLists.txt
- examples/qml_minimal/CMakeLists.txt
- examples/qml_multi_crates/CMakeLists.txt
- tests/basic_cxx_only/CMakeLists.txt
- tests/basic_cxx_qt/CMakeLists.txt
- tests/qt_types_standalone/CMakeLists.txt
- **MSVC: Link Qt components to Release runtime**
- **Windows CI: Build Qt6 in Debug**
> MSVC: Use Qt Release runtime

- Cargo.lock
- crates/cxx-qt-macro/Cargo.toml
- crates/cxx-qt-macro/src/lib.rs
- crates/cxx-qt/src/lib.rs
cxx-qt-macro needed cxx-qt as a dev-dependency for the documentation.
This didn't allow me to release the crate, as cxx-qt-macro depended on
cxx-qt 0.7.2, which wasn't released yet, but cxx-qt itself also depended
on cxx-qt-macro 0.7.2 which also wasn't released yet.
We can solve this conundrum by moving the documentation of cxx-qt-macro
into cxx-qt itself.
The documentation of cxx-qt-macro should not be used anyway, as it is an
implementation detail.
> Remove cxx-qt dependency of cxx-qt-macro

- crates/cxx-qt/src/lib.rs
- examples/cargo_without_cmake/src/main.rs
- examples/qml_multi_crates/rust/main/src/main.rs
Suppose a user creates a function like this:
```rust
fn do_something<T: Upcast<MyObject>>(object: &T);
```
It should be possible to call `do_something(object)` where `object` *is* `&MyObject`.
The `Upcast<Self>` implementations are all no-ops.
> Automatically implement Upcast<Self> for all types

- CHANGELOG.md
- crates/cxx-qt-lib-extras/build.rs
- crates/cxx-qt-lib-extras/include/core/qeventloop.h
- crates/cxx-qt-lib-extras/src/core/mod.rs
- crates/cxx-qt-lib-extras/src/core/qeventloop.rs
I've been finding [`QEventLoop`](https://doc.qt.io/qt-6/qeventloop.html) useful in my own projects, especially for unit testing, so I figured I'd make a PR to add it to cxx-qt-lib-extras if other people would find it useful as well. The neat thing about `QEventLoop` is that it can be used for nested local event processing rather than needing to rely on `QApplication::exec` and all the baggage it brings. For example, you can run the event loop in Rust without needing to delegate to C++ at all, which is very useful for unit tests:
```rs
fn wait_for_encrypted(socket: &QSslSocket, timeout: Duration) -> bool {
let now = Instant::now();
let mut event_loop = QEventLoop::new();
loop {
event_loop.pin_mut().process_all_events();
if socket.is_encrypted() {
return true;
}
if now.elapsed() > timeout { …
```
> Add QEventLoop to cxx-qt-lib-extras

- crates/cxx-qt-lib/build.rs
- crates/cxx-qt-lib/include/core/qobject.h
- crates/cxx-qt-lib/src/core/mod.rs
- crates/cxx-qt-lib/src/core/qobject.rs
- crates/cxx-qt-lib/src/core/qstring.rs
- crates/cxx-qt/src/qobject.rs
- cxx-qt-lib trait for additional qobject wrappers
Closes #562 
The added methods are:
- blockSignals
- signalsBlocked
- setObjectName
- objectName
- parent
- setParent
> Add qobject extension trait

- CHANGELOG.md
- crates/cxx-qt-lib/src/core/mod.rs
- crates/cxx-qt-lib/src/core/qtlogging.rs
This adds two new global functions available in <QtLogging>: [qFormatLogMessage](https://doc.qt.io/qt-6/qtlogging.html#qFormatLogMessage) and [qSetMessagePattern](https://doc.qt.io/qt-6/qtlogging.html#qSetMessagePattern).
qFormatLogMessage is similar to qt_message_output, but actually documented. Instead of going to the default message handler though, it outputs to a QString. This is probably not useful without message handler support, but it's easy to expose.
qSetMessagePattern is very useful, as it allows CXX-Qt applications to set custom Qt message patterns for logging.
> cxx-qt-lib: Add two more QtLogging functions

- crates/cxx-qt-lib/src/core/qflags/mod.rs
A `QFlags` is just a wrapper around an integer, so it should always implement `Eq`, `Ord`, etc. However, derived implementations apply their constraints to all type arguments, which means that currently, `QFlags<T>` only implements `Ord` if `T` implements `Ord`, and so on. There's no reason to have those bounds, so I removed them.
> Remove unnecessary constraints from QFlags derived implementations

- CHANGELOG.md
- crates/cxx-qt-gen/src/generator/rust/property/mod.rs
- crates/cxx-qt-gen/src/generator/rust/signals.rs
- crates/cxx-qt-gen/test_outputs/cfgs.rs
- crates/cxx-qt-gen/test_outputs/passthrough_and_naming.rs
- crates/cxx-qt-gen/test_outputs/properties.rs
- crates/cxx-qt-gen/test_outputs/signals.rs
- crates/cxx-qt-lib/src/core/mod.rs
- crates/cxx-qt/src/connection.rs
- crates/cxx-qt/src/connectionguard.rs
- crates/cxx-qt/src/lib.rs
- crates/cxx-qt/src/signalhandler.rs
- examples/qml_features/rust/src/signals.rs
- tests/qt_types_standalone/rust/src/qmetaobjectconnection.rs
Instead of requiring `'static` closures, connection signal handlers now accept lifetime parameters:
```rs
pub fn on_mysignal<'a, F>(self: Pin<&mut Self>, closure: F) -> QMetaObjectConnectionGuard<'a>
where
F: FnMut(Pin<&mut Self>) + 'a + Send,
```
This makes it possible to attach callbacks to signals that use scoped variables. Only `QMetaObjectConnectionGuard<'static>` can use `.release()`, so the Drop implementation will ensure all other closures are disconnected once their lifetimes have expired.
> Add a lifetime parameter to QMetaObjectConnectionGuard

- .github/workflows/github-cxx-qt-tests.yml
This should enable only a single workflow run per branch (including
main) to run at the same time.
If we're landing multiple commits via merge queue, it should force the
newest one to be tested only.
> CI: Limit concurrency to one per ref_name

- crates/cxx-qt-lib/Cargo.toml
- crates/cxx-qt-lib/src/lib.rs
Currently, [cxx-qt-lib's docs.rs page](https://docs.rs/cxx-qt-lib/latest/cxx_qt_lib/) does not document any types that are gated behind features. This PR fixes the issue.
> Document types that require features

- crates/cxx-qt-lib/src/core/qdate.rs
- crates/cxx-qt-lib/src/core/qdatetime.rs
- crates/cxx-qt-lib/src/core/qmodelindex.rs
- tests/qt_types_standalone/rust/src/qmodelindex.rs
Somehow I missed a bunch of `qint64`s in #1267.
> Replace remaining uses of qint64

- CHANGELOG.md
- crates/cxx-qt-lib/include/core/qbytearray.h
- crates/cxx-qt-lib/src/core/mod.rs
- crates/cxx-qt-lib/src/core/qbytearray.cpp
- crates/cxx-qt-lib/src/core/qbytearray.rs
Qt documentation:
- [QByteArray::fromBase64Encoding](https://doc.qt.io/qt-6/qbytearray.html#fromBase64Encoding)
- [QByteArray:toBase64](https://doc.qt.io/qt-6/qbytearray.html#toBase64)
> Add QByteArray:from_base64_encoding and QByteArray::to_base64

- crates/cxx-qt-lib/src/core/qobject.rs
> Require the argument passed to QObjectExt::set_parent to be mutable

- .github/workflows/github-cxx-qt-tests.yml
This gets rid of all those messages like
```
warning: qml_features@0.1.0: [2025-07-19T16:17:37Z DEBUG sccache::config] Attempting to read config file at "/home/runner/.config/sccache/config"
```
that make it incredibly difficult to spot why tests fail.
> Improve CI log readability by removing sccache debug statements

- .github/workflows/github-cxx-qt-tests.yml
- CHANGELOG.md
- Cargo.toml
- book/src/getting-started/5-cmake-integration.md
- codecov.yml
- crates/cxx-qt-build/src/diagnostics.rs
- crates/cxx-qt-build/src/lib.rs
- crates/cxx-qt-gen/src/generator/cpp/method.rs
- crates/cxx-qt-gen/src/generator/cpp/qenum.rs
- crates/cxx-qt-gen/src/generator/cpp/qobject.rs
- crates/cxx-qt-gen/src/generator/rust/mod.rs
- crates/cxx-qt-gen/src/generator/rust/qenum.rs
- crates/cxx-qt-gen/src/generator/rust/threading.rs
- crates/cxx-qt-gen/src/lib.rs
- crates/cxx-qt-gen/src/parser/trait_impl.rs
- crates/cxx-qt-gen/src/syntax/qtitem.rs
- crates/cxx-qt-gen/src/writer/cpp/header.rs
- crates/cxx-qt-gen/src/writer/cpp/mod.rs
- crates/cxx-qt-gen/src/writer/rust/mod.rs
- crates/cxx-qt-gen/test_outputs/invokables.rs
- crates/cxx-qt-gen/test_outputs/qenum.h
- crates/cxx-qt-gen/test_outputs/qenum.rs
- crates/cxx-qt-macro/Cargo.toml
- crates/cxx-qt-macro/src/lib.rs
- crates/cxx-qt/src/lib.rs
- crates/cxx-qt/src/threading.rs
- crates/qt-build-utils/src/lib.rs
- examples/qml_features/rust/src/properties.rs
- examples/qml_features/rust/src/signals.rs
- tests/qt_types_standalone/rust/src/qanystringview.rs
- **threading: fix `mutable reference to C++ type requires a pin` in drop**
- **Remove cxx-qt dependency of cxx-qt-macro**
- **Refactor QEnum generation to return fragments**
- **Fix QEnum generation for Qt 6.9.2**
- **Bump version to 0.7.3**
> CXX-Qt 0.7.3 backports
